// ITS Data columns - all filterable fields
export const ITS_COLUMNS = [
  { id: "ITS_ID", label: "ITS ID", type: "string" },
  { id: "HOF_FM_TYPE", label: "HOF/FM Type", type: "string" },
  { id: "HOF_ID", label: "HOF ID", type: "string" },
  { id: "Family_ID", label: "Family ID", type: "string" },
  { id: "Father_ITS_ID", label: "Father ITS ID", type: "string" },
  { id: "Mother_ITS_ID", label: "Mother ITS ID", type: "string" },
  { id: "Spouse_ITS_ID", label: "Spouse ITS ID", type: "string" },
  { id: "TanzeemFile_No", label: "Tanzeem File No", type: "string" },
  { id: "Full_Name", label: "Full Name", type: "string" },
  { id: "Full_Name_Arabic", label: "Full Name (Arabic)", type: "string" },
  { id: "First_Prefix", label: "First Prefix", type: "string" },
  { id: "Prefix_Year", label: "Prefix Year", type: "string" },
  { id: "First_Name", label: "First Name", type: "string" },
  { id: "Father_Prefix", label: "Father Prefix", type: "string" },
  { id: "Father_Name", label: "Father Name", type: "string" },
  { id: "Father_Surname", label: "Father Surname", type: "string" },
  { id: "Husband_Prefix", label: "Husband Prefix", type: "string" },
  { id: "Husband_Name", label: "Husband Name", type: "string" },
  { id: "Surname", label: "Surname", type: "string" },
  { id: "Age", label: "Age", type: "number" },
  { id: "Gender", label: "Gender", type: "string" },
  { id: "Misaq", label: "Misaq", type: "string" },
  { id: "Marital_Status", label: "Marital Status", type: "string" },
  { id: "Blood_Group", label: "Blood Group", type: "string" },
  { id: "Warakatul_Tarkhis", label: "Warakatul Tarkhis", type: "string" },
  { id: "Date_Of_Nikah", label: "Date of Nikah", type: "string" },
  { id: "Date_Of_Nikah_Hijri", label: "Date of Nikah (Hijri)", type: "string" },
  { id: "Mobile", label: "Mobile", type: "string" },
  { id: "Email", label: "Email", type: "string" },
  { id: "Title", label: "Title", type: "string" },
  { id: "Category", label: "Category", type: "string" },
  { id: "Idara", label: "Idara", type: "string" },
  { id: "Organisation", label: "Organisation", type: "string" },
  { id: "Organisation_CSV", label: "Organisation CSV", type: "string" },
  { id: "Vatan", label: "Vatan", type: "string" },
  { id: "Nationality", label: "Nationality", type: "string" },
  { id: "Jamaat", label: "Jamaat", type: "string" },
  { id: "Jamiaat", label: "Jamiaat", type: "string" },
  { id: "Qualification", label: "Qualification", type: "string" },
  { id: "Languages", label: "Languages", type: "string" },
  { id: "Hunars", label: "Hunars", type: "string" },
  { id: "Occupation", label: "Occupation", type: "string" },
  { id: "Sub_Occupation", label: "Sub Occupation", type: "string" },
  { id: "Sub_Occupation2", label: "Sub Occupation 2", type: "string" },
  { id: "Quran_Sanad", label: "Quran Sanad", type: "string" },
  { id: "Qadambosi_Sharaf", label: "Qadambosi Sharaf", type: "string" },
  {
    id: "Raudat_Tahera_Ziyarat",
    label: "Raudat Tahera Ziyarat",
    type: "string",
  },
  { id: "Karbala_Ziyarat", label: "Karbala Ziyarat", type: "string" },
  { id: "Ashara_Mubaraka", label: "Ashara Mubaraka", type: "number" },
  { id: "Housing", label: "Housing", type: "string" },
  { id: "Type_of_House", label: "Type of House", type: "string" },
  { id: "Address", label: "Address", type: "string" },
  { id: "Building", label: "Building", type: "string" },
  { id: "Street", label: "Street", type: "string" },
  { id: "Area", label: "Area", type: "string" },
  { id: "State", label: "State", type: "string" },
  { id: "City", label: "City", type: "string" },
  { id: "Pincode", label: "Pincode", type: "string" },
  { id: "Sector", label: "Sector", type: "string" },
  { id: "Sub_Sector", label: "Sub Sector", type: "string" },
  { id: "Inactive_Status", label: "Inactive Status", type: "string" },
  {
    id: "Data_Verifcation_Status",
    label: "Data Verification Status",
    type: "string",
  },
  {
    id: "Data_Verification_Date",
    label: "Data Verification Date",
    type: "string",
  },
  {
    id: "Photo_Verifcation_Status",
    label: "Photo Verification Status",
    type: "string",
  },
  {
    id: "Photo_Verification_Date",
    label: "Photo Verification Date",
    type: "string",
  },
  { id: "Last_Scanned_Event", label: "Last Scanned Event", type: "string" },
  { id: "Last_Scanned_Place", label: "Last Scanned Place", type: "string" },
  {
    id: "Sector_Incharge_ITSID",
    label: "Sector Incharge ITS ID",
    type: "string",
  },
  { id: "Sector_Incharge_Name", label: "Sector Incharge Name", type: "string" },
  {
    id: "Sector_Incharge_Female_ITSID",
    label: "Sector Incharge Female ITS ID",
    type: "string",
  },
  {
    id: "Sector_Incharge_Female_Name",
    label: "Sector Incharge Female Name",
    type: "string",
  },
  {
    id: "Sub_Sector_Incharge_ITSID",
    label: "Sub Sector Incharge ITS ID",
    type: "string",
  },
  {
    id: "Sub_Sector_Incharge_Name",
    label: "Sub Sector Incharge Name",
    type: "string",
  },
  {
    id: "Sub_Sector_Incharge_Female_ITSID",
    label: "Sub Sector Incharge Female ITS ID",
    type: "string",
  },
  {
    id: "Sub_Sector_Incharge_Female_Name",
    label: "Sub Sector Incharge Female Name",
    type: "string",
  },
];

// Operators based on field type
export const STRING_OPERATORS = [
  { id: "equals", label: "Equals" },
  { id: "notEquals", label: "Not Equals" },
  { id: "contains", label: "Contains" },
  { id: "notContains", label: "Not Contains" },
  { id: "startsWith", label: "Starts With" },
  { id: "endsWith", label: "Ends With" },
  { id: "in", label: "In (multiple values)" },
  { id: "notIn", label: "Not In (multiple values)" },
  { id: "isEmpty", label: "Is Empty" },
  { id: "isNotEmpty", label: "Is Not Empty" },
];

export const NUMBER_OPERATORS = [
  { id: "equals", label: "Equals" },
  { id: "notEquals", label: "Not Equals" },
  { id: "greaterThan", label: "Greater Than" },
  { id: "greaterThanOrEqual", label: "Greater Than Or Equal" },
  { id: "lessThan", label: "Less Than" },
  { id: "lessThanOrEqual", label: "Less Than Or Equal" },
  { id: "in", label: "In (multiple values)" },
  { id: "notIn", label: "Not In (multiple values)" },
  { id: "isEmpty", label: "Is Empty" },
  { id: "isNotEmpty", label: "Is Not Empty" },
];

export const getOperatorsForType = (type) =>
  type === "number" ? NUMBER_OPERATORS : STRING_OPERATORS;
