export const fm = [
  [{ age: "34", its: "30375217", name: "Juzer Kapadia", gender: "Male" }],
  [
    {
      age: "76",
      its: "20372588",
      name: "Firoz bhai Akberali bhai Aurangabad wala",
      gender: "Male",
    },
  ],
  [
    { age: "52", its: "30368087", name: "Asma bai Husain bhai Firangi", gender: "Female" },
    { age: "26", its: "30368088", name: "Alefiyah bai Husain bhai Firangi", gender: "Female" },
    { age: "21", its: "30368089", name: "Ummekulsum bai Husain bhai Firagi", gender: "Female" },
  ],
  [
    {
      age: "24",
      its: "30374295",
      name: "Tasneem bai Mohammedhussain bhai Burhanpur wala",
      gender: "Female",
    },
    {
      age: "26",
      its: "60464488",
      name: "Mohammedhussain bhai Altafhusain bhai Burhanpur wala",
      gender: "Male",
    },
    { age: "67", its: "30374244", name: "Fatema Ezzi", gender: "Female" },
  ],
  [
    {
      age: "57",
      its: "30377793",
      name: "Shoeb bhai Mohammedhusain bhai Rampurawala",
      gender: "Male",
    },
    { age: "46", its: "30377794", name: "Shehrebanu bai Shoeb bhai Rampurawala", gender: "Female" },
    { age: "18", its: "30705374", name: "Mariyah bai Shoeb bhai Rampurawala", gender: "Female" },
    { age: "81", its: "30377795", name: "Kulsum Rampurawala", gender: "Female" },
  ],
  [{ age: "19", its: "60446280", name: "Muffadal Garhiwala", gender: "Male" }],
  [
    { age: "22", its: "30493135", name: "Husain Andheriwala", gender: "Male" },
    { age: "22", its: "30399511", name: "Taher Calcutta", gender: "Male" },
    { age: "22", its: "30501295", name: "Taha Dungarpurwala", gender: "Male" },
    { age: "22", its: "30399627", name: "Burhanuddin Rasulji", gender: "Male" },
    { age: "22", its: "30396408", name: "Husain Gundar", gender: "Male" },
    { age: "22", its: "30396554", name: "husain ghadiali", gender: "Male" },
    { age: "22", its: "30396025", name: "Taha Borigam", gender: "Male" },
    { age: "22", its: "50401761", name: "Ilyas Udaipurwala", gender: "Male" },
  ],
  [
    { age: "24", its: "50434962", name: "Yusuf bhai Hunaid bhai Nagarwala", gender: "Male" },
    { age: "22", its: "50434963", name: "Zainab bai Hunaid bhai Nagarwala", gender: "Female" },
    { age: "22", its: "50434964", name: "Husain bhai Hunaid bhai Nagarwala", gender: "Male" },
  ],
  [
    {
      age: "75",
      its: "20326085",
      name: "Shaikh Hatim bhai Mukhtaar bhai Jabalpurwala",
      gender: "Male",
    },
    {
      age: "61",
      its: "60461223",
      name: "Tasneem bai Shaikh Hatim bhai Jabalpurwala",
      gender: "Female",
    },
  ],
  [
    { age: "69", its: "30313569", name: "Nafisa bai Husain bhai Bhavnagarwala", gender: "Female" },
    { age: "38", its: "30313575", name: "Juzer bhai Husain bhai Bhavnagarwala", gender: "Male" },
    { age: "32", its: "30463695", name: "Arwa bai Juzer bhai Bhavnagarwala", gender: "Female" },
    {
      age: "8",
      its: "40156387",
      name: "Burhanuddin bhai Juzer bhai Bhavnagarwala",
      gender: "Male",
    },
  ],
  [
    { age: "63", its: "20356831", name: "Shabbir Bhai Jarwala", gender: "Male" },
    { age: "29", its: "30491576", name: "ADnan Jarwala", gender: "Male" },
    { age: "25", its: "50423900", name: "Fatema JArwala", gender: "Female" },
  ],
  [
    {
      age: "68",
      its: "20375972",
      name: "Husain bhai Fakhruddin bhai Fatehpurwala",
      gender: "Male",
    },
    { age: "32", its: "40435775", name: "Batul bai Shabbir bhai Fatepurwala", gender: "Female" },
  ],
  [
    {
      age: "34",
      its: "30373436",
      name: "Hussain bhai Shaikh Abbas bhai Dungarpurwala",
      gender: "Male",
    },
    {
      age: "8",
      its: "50160930",
      name: "Hussaina bai Hussain bhai Dungarpurwala",
      gender: "Female",
    },
    {
      age: "30",
      its: "60469429",
      name: "Durriya bai Hussain bhai Dungarpurwala",
      gender: "Female",
    },
  ],
  [
    {
      age: "61",
      its: "20325975",
      name: "Saifuddin bhai Mulla Shabbir bhai Akolawala",
      gender: "Male",
    },
  ],
  [
    {
      age: "76",
      its: "20431342",
      name: "Mulla Saifuddin bhai Abdulhusain bhai Electricwala",
      gender: "Male",
    },
    {
      age: "46",
      its: "30375940",
      name: "Mustafa bhai Mulla Saifuddin bhai Electricwala",
      gender: "Male",
    },
    {
      age: "67",
      its: "30375941",
      name: "Rehana bai Mulla Saifuddin bhai Electricwala",
      gender: "Female",
    },
  ],
  [{ age: "79", its: "20335956", name: "Tasdiqhusain bhai Asgarali bhai Raja", gender: "Male" }],
  [
    { age: "47", its: "30376240", name: "Tasneem bai Salim bhai Ghadialy", gender: "Female" },
    { age: "26", its: "30376241", name: "Arwa Ghadially", gender: "Female" },
  ],
  [
    { age: "29", its: "30487763", name: "Zainab bai Juzer bhai Chadderwala", gender: "Female" },
    { age: "24", its: "30908518", name: "Amatullah bai Sajjad bhai Poonawala", gender: "Female" },
    { age: "30", its: "30908521", name: "Qusai bhai Sajjad bhai Poonawala", gender: "Male" },
    { age: "56", its: "30908522", name: "Amina bai Sajjad bhai Poonawala", gender: "Female" },
    { age: "67", its: "20407529", name: "Zujar yusufali", gender: "Male" },
  ],
  [
    { age: "42", its: "30395664", name: "Murtaza bhai Moiz bhai Haveliwala", gender: "Male" },
    { age: "36", its: "30448707", name: "Shireen bai Murtaza bhai Haveliwala", gender: "Female" },
  ],
  [
    { age: "52", its: "20406290", name: "Mulla Hatim bhai Ali bhai Ghadiyali", gender: "Male" },
    { age: "48", its: "30488717", name: "Tahera bai Mulla Hatim bhai Ghadiyali", gender: "Female" },
    { age: "21", its: "30488719", name: "Sakina bai Mulla Hatim bhai Ghadiyali", gender: "Female" },
    { age: "17", its: "30710976", name: "Husain bhai Mulla Hatim bhai Ghadiyali", gender: "Male" },
  ],
  [
    { age: "27", its: "30373515", name: "Murtaza Adenwala", gender: "Male" },
    { age: "18", its: "40900502", name: "Sakina Adenwala", gender: "Female" },
  ],
  [
    { age: "12", its: "30151897", name: "Alefiya bai Husain bhai Banglawala", gender: "Female" },
    { age: "17", its: "30700403", name: "Shabbir bhai Husain bhai Banglawala", gender: "Male" },
    {
      age: "75",
      its: "60411793",
      name: "Jamila bai Mohammadhusain bhai Banglawala",
      gender: "Female",
    },
  ],
  [{ age: "36", its: "50473456", name: "Jumana bai Huzaifa bhai Sukhiwala", gender: "Female" }],
  [
    { age: "29", its: "30423465", name: "Aliasger Vohra", gender: "Male" },
    { age: "25", its: "30423466", name: "Fatema Vohra", gender: "Female" },
    { age: "25", its: "50498553", name: "Tasneem Vohra", gender: "Female" },
    { age: "18", its: "60429666", name: "Husen Bodeliwala", gender: "Male" },
    { age: "42", its: "30709204", name: "Husain Bodeliwala", gender: "Male" },
    { age: "48", its: "60463387", name: "Habib Gojipurwala", gender: "Male" },
    { age: "17", its: "40903670", name: "Zainuddin Gojipurwala", gender: "Male" },
    { age: "45", its: "60463388", name: "Nadeali Gojipurwala", gender: "Male" },
    { age: "55", its: "60463370", name: "Huseni Gojipurwala", gender: "Male" },
  ],
  [
    { age: "49", its: "30373810", name: "Nafisa bai Huzaifa bhai Chopadawala", gender: "Female" },
    { age: "55", its: "30373811", name: "Huzaifa bhai Asgar bhai Chopadawala", gender: "Male" },
    { age: "17", its: "40800195", name: "Fatema bai Huzaifa bhai Chopadawala", gender: "Female" },
    { age: "19", its: "40800196", name: "Taher bhai Huzaifa bhai Chopadawala", gender: "Male" },
    { age: "24", its: "40407752", name: "Munira Talib Godhrawala", gender: "Female" },
  ],
  [
    { age: "52", its: "20320034", name: "Mustafa bhai Hatim bhai Kothari", gender: "Male" },
    { age: "23", its: "30384089", name: "Ibrahim bhai Mustafa bhai Kothari", gender: "Male" },
    { age: "21", its: "30384090", name: "Hasan bhai Mustafa bhai Kothari", gender: "Male" },
    { age: "48", its: "30601510", name: "Fatema bai Mustafa bhai Kothari", gender: "Female" },
    { age: "25", its: "30601511", name: "Rashida Rajkotwala", gender: "Female" },
    { age: "29", its: "30327328", name: "Murtaza Rajkotwala", gender: "Male" },
  ],
  [
    {
      age: "86",
      its: "20325740",
      name: "Shaikh Saifuddin bhai Shaikh Taiyebali bhai Jamali",
      gender: "Male",
    },
    { age: "49", its: "20389690", name: "Abid bhai Shaikh Saifuddin bhai Jamali", gender: "Male" },
    { age: "44", its: "30387935", name: "Zainab bai Abid bhai Jamali", gender: "Female" },
    { age: "21", its: "30601592", name: "Qaidjoher bhai Abid bhai Jamali", gender: "Male" },
    { age: "15", its: "40800477", name: "Burhanuddin bhai Abid bhai Jamali", gender: "Male" },
  ],
  [
    { age: "66", its: "30478559", name: "Fatema bai Fakhruddin bhai Diwan", gender: "Female" },
    { age: "40", its: "30478560", name: "Yusuf bhai Fakhruddin bhai Diwan", gender: "Male" },
  ],
  [
    {
      age: "10",
      its: "30117798",
      name: "Nisreen bai Mohammed bhai Bhikhapurwala",
      gender: "Female",
    },
    {
      age: "6",
      its: "30180108",
      name: "Burhanuddin bhai Mohammed bhai Bhikhapurwala",
      gender: "Male",
    },
    {
      age: "32",
      its: "30489342",
      name: "Nafisa bai Mohammed bhai Bhikhapurwala",
      gender: "Female",
    },
    {
      age: "35",
      its: "60430957",
      name: "Mohammed bhai Saifuddin bhai Bhikhapurwala",
      gender: "Male",
    },
  ],
  [
    { age: "71", its: "20326801", name: "Shk Nuruddin Mandlawala", gender: "Male" },
    { age: "65", its: "60461616", name: "Arwa Shk Nooruddin", gender: "Female" },
  ],
  [
    {
      age: "61",
      its: "20405731",
      name: "Abduttayyeb bhai Abdulhusain bhai Hathai",
      gender: "Male",
    },
  ],
  [
    {
      age: "57",
      its: "40407624",
      name: "Aliasgar bhai Mohammadhussain bhai Rampurawala",
      gender: "Male",
    },
    { age: "49", its: "40407625", name: "Tasneem bai Aliasgar bhai Rampurawala", gender: "Female" },
    { age: "23", its: "40407639", name: "Mustafa bhai Aliasgar bhai Rampurawala", gender: "Male" },
  ],
  [{ age: "57", its: "30705087", name: "Mustafa bhai Moiz bhai Rakla", gender: "Male" }],
  [
    { age: "64", its: "20325657", name: "Abbas bhai Saifuddin bhai Poonawala", gender: "Male" },
    { age: "58", its: "30375672", name: "Farida bai Abbas bhai Poonawala", gender: "Female" },
  ],
  [
    { age: "40", its: "30448758", name: "Tasneem bai Adnan bhai Master", gender: "Female" },
    { age: "46", its: "30484279", name: "Adnan bhai Nooruddin bhai Master", gender: "Male" },
    { age: "18", its: "30910791", name: "Qaizar bhai Adnan bhai Master", gender: "Male" },
    { age: "13", its: "40911477", name: "Mustafa bhai Adnan bhai Master", gender: "Male" },
  ],
  [
    { age: "8", its: "30152480", name: "Burhanuddin bhai Mustafa bhai Noble", gender: "Male" },
    {
      age: "32",
      its: "30318954",
      name: "Umaima bai Mulla Abduttaiyab bhai Noble",
      gender: "Female",
    },
    { age: "37", its: "30322402", name: "Arwa bai Mulla Huzaifa bhai Noble", gender: "Female" },
    {
      age: "40",
      its: "30377423",
      name: "Mulla Huzaifa bhai Shaikh Quraish bhai Noble",
      gender: "Male",
    },
    {
      age: "37",
      its: "30377424",
      name: "Mulla Abduttaiyab bhai Shaikh Quraish bhai Noble",
      gender: "Male",
    },
    { age: "33", its: "30377425", name: "Mustafa bhai Shaikh Quraish bhai Noble", gender: "Male" },
    { age: "61", its: "30377426", name: "Munira bai Shaikh Quraish bhai Noble", gender: "Female" },
    { age: "34", its: "30470297", name: "Insiyah bai Mustafa bhai Noble", gender: "Female" },
    { age: "15", its: "30914409", name: "Murtaza bhai Mulla Huzaifa bhai Noble", gender: "Male" },
    { age: "13", its: "30914410", name: "Sakina bai Mulla Huzaifa bhai Noble", gender: "Female" },
    {
      age: "11",
      its: "40151785",
      name: "Mufaddal bhai Mulla Abduttaiyab bhai Noble",
      gender: "Male",
    },
    { age: "8", its: "40153518", name: "Zahra bai Mulla Abduttaiyab bhai Noble", gender: "Female" },
  ],
  [
    { age: "53", its: "30905158", name: "Quraish Primus", gender: "Male" },
    { age: "43", its: "30912199", name: "Munira Primus", gender: "Female" },
    { age: "26", its: "30912189", name: "Tasneem Munshi", gender: "Female" },
    { age: "24", its: "30912198", name: "Husain Primus", gender: "Male" },
    { age: "21", its: "30912190", name: "Amatullah Primus ", gender: "Female" },
  ],
  [
    { age: "53", its: "20352053", name: "Abbas bhai Mulla Fakhruddin bhai Mala", gender: "Male" },
    { age: "23", its: "30389502", name: "Amatullah bai Abdulqadir bhai Mala", gender: "Female" },
    { age: "51", its: "30464801", name: "Tasneem bai Abbas bhai Mala", gender: "Female" },
  ],
  [
    { age: "9", its: "30118327", name: "Batul bai Mulla Murtaza bhai Pacha", gender: "Female" },
    { age: "45", its: "30374908", name: "Mulla Murtaza bhai Muslim bhai Pacha", gender: "Male" },
    { age: "41", its: "30376404", name: "Munira bai Mulla Murtaza bhai Pacha", gender: "Female" },
    { age: "12", its: "40910086", name: "Insiyah bai Mulla Murtaza bhai Pacha", gender: "Female" },
  ],
  [
    { age: "25", its: "30316209", name: "Tasneem bai Moiz bhai Machinewala", gender: "Female" },
    {
      age: "55",
      its: "30324451",
      name: "Durriya bai Abdulhusain bhai Machinewala",
      gender: "Female",
    },
    { age: "28", its: "30324453", name: "Moiz bhai Abdulhusain bhai Machinewala", gender: "Male" },
  ],
  [
    {
      age: "51",
      its: "20322731",
      name: "Mulla Shabbir bhai Shaikh Qutbuddin bhai Jawad wala",
      gender: "Male",
    },
    {
      age: "22",
      its: "30385279",
      name: "Mufaddal bhai Mulla Shabbir bhai Jawad wala",
      gender: "Male",
    },
    {
      age: "50",
      its: "30385280",
      name: "Sakina bai Mulla Shabbir bhai Jawad wala",
      gender: "Female",
    },
    {
      age: "16",
      its: "40800003",
      name: "Jamila bai Mulla Shabbir bhai Jawad wala",
      gender: "Female",
    },
    { age: "81", its: "20300770", name: "Shk Qutubuddin Jawadwala", gender: "Male" },
  ],
  [
    {
      age: "55",
      its: "20326175",
      name: "Zainuddin bhai Mulla Husain bhai Khanwala",
      gender: "Male",
    },
    { age: "26", its: "30409230", name: "Ruqaiyah bai Hasan bhai Khanwala", gender: "Female" },
    { age: "51", its: "60461354", name: "Munira bai Zainuddin bhai Khanwala", gender: "Female" },
    { age: "25", its: "60461355", name: "Huzaifa bhai Zainuddin bhai Khanwala", gender: "Male" },
    { age: "27", its: "60461356", name: "Hasan bhai Zainuddin bhai Khanwala", gender: "Male" },
  ],
  [
    { age: "31", its: "40452252", name: "Mustafa bhai Aliasgar bhai Rangoonwala", gender: "Male" },
    { age: "27", its: "50477392", name: "Naqiyah bai Mustafa bhai Rangoonwala", gender: "Female" },
  ],
  [
    { age: "43", its: "30344171", name: "Alefiyah bai Murtaza bhai Ghadiali", gender: "Female" },
    { age: "17", its: "30705356", name: "Husaina bai Murtaza bhai Ghadiyali", gender: "Female" },
    { age: "46", its: "60422209", name: "Murtaza bhai Hatim bhai Ghadiali", gender: "Male" },
  ],
  [
    { age: "33", its: "30399889", name: "Naqiyah bai Mufaddal bhai Gulshan", gender: "Female" },
    {
      age: "34",
      its: "30460074",
      name: "Mufaddal bhai Shaikh Abdulhusain bhai Gulshan",
      gender: "Male",
    },
    {
      age: "68",
      its: "30460092",
      name: "Rehana bai Shaikh Abdulhusain bhai Gulshan",
      gender: "Female",
    },
    { age: "6", its: "40182148", name: "Husain bhai Mufaddal bhai Gulshan", gender: "Male" },
  ],
  [
    { age: "79", its: "20302134", name: "Taher bhai Saifuddin bhai Lokhandwala", gender: "Male" },
    { age: "48", its: "20326514", name: "Murtaza bhai Taher bhai Lokhandwala", gender: "Male" },
    { age: "19", its: "30801924", name: "Adnan bhai Murtaza bhai Lokhandwala", gender: "Male" },
  ],
  [
    { age: "34", its: "30370416", name: "Mariyah bai Mohammed bhai Malkan", gender: "Female" },
    { age: "9", its: "50190573", name: "Sarah bai Mohammed bhai Malkan", gender: "Female" },
  ],
  [
    { age: "50", its: "60446595", name: "Nisreen Ben Rahim", gender: "Female" },
    { age: "18", its: "60482012", name: "Sakina Ben Rahim", gender: "Female" },
  ],
  [
    { age: "48", its: "30709013", name: "Mohammed bhai Shabbir bhai Madraswala", gender: "Male" },
    { age: "43", its: "30709014", name: "Zainab bai Mohammed bhai Madraswala", gender: "Female" },
    { age: "19", its: "30709015", name: "Taher bhai Mohammed bhai Madraswala", gender: "Male" },
  ],
  [
    { age: "45", its: "30358938", name: "Fatema Valibhai", gender: "Female" },
    { age: "40", its: "60455284", name: "Fatema Valibhai", gender: "Female" },
    { age: "30", its: "40447859", name: "Amatullah Kaid", gender: "Female" },
    { age: "30", its: "60481060", name: "Sarrah Mohammed", gender: "Female" },
    { age: "30", its: "50470844", name: "Naqiyah Qutubuddin", gender: "Female" },
    { age: "30433258", its: "30433258", name: "Jamila Mustafa", gender: "Female" },
    { age: "30", its: "40801370", name: "Sarrah ", gender: "Female" },
    { age: "25", its: "40801371", name: "Fatema ", gender: "Female" },
    { age: "25", its: "30442528", name: "Zainab ", gender: "Female" },
    { age: "25", its: "30488479", name: "Zainab Kapasi", gender: "Female" },
  ],
  [
    { age: "50", its: "30351227", name: "Husain bhai Hakimuddin bhai Batterywala", gender: "Male" },
    { age: "44", its: "30351228", name: "Fatema bai Husain bhai Batterywala", gender: "Female" },
    { age: "82", its: "20312202", name: "Hakimuddin Batterywala", gender: "Male" },
  ],
  [
    { age: "39", its: "30373593", name: "Husain bhai Mohammed bhai Tambuwala", gender: "Male" },
    { age: "36", its: "40407490", name: "Jamila bai Husain bhai Tambuwala", gender: "Female" },
  ],
  [
    { age: "58", its: "20326065", name: "Ilyas bhai Husain bhai Khedwala", gender: "Male" },
    { age: "50", its: "30377754", name: "Nisreen bai Ilyas bhai Khedwala", gender: "Female" },
    { age: "32", its: "30377755", name: "Fatema bai Ilyas bhai Khedwala", gender: "Female" },
  ],
  [
    { age: "21", its: "30374367", name: "Fatema bai Murtaza bhai Sarodawala", gender: "Female" },
    { age: "87", its: "30377184", name: "Fatema bai Alihusain bhai Saroda", gender: "Female" },
    { age: "30", its: "30377188", name: "Murtaza bhai Shabbir bhai Sarodawala", gender: "Male" },
    { age: "27", its: "30377189", name: "Aliakbar bhai Shabbir bhai Sarodawala", gender: "Male" },
    { age: "52", its: "30377190", name: "Munira bai Shabbir bhai Sarodawala", gender: "Female" },
    { age: "58", its: "30377192", name: "Shabbir bhai Alihusain bhai Sarodawala", gender: "Male" },
    { age: "25", its: "30493373", name: "Insiyah bai Aliakbar bhai Sarodawala", gender: "Female" },
  ],
  [
    { age: "30", its: "50483906", name: "Hussain Pansoliwala", gender: "Male" },
    { age: "27", its: "50481514", name: "Zainab Pansoliwala", gender: "Female" },
  ],
  [
    {
      age: "23",
      its: "30477393",
      name: "Hakimuddin bhai Mulla Abbas bhai Rampurawala",
      gender: "Male",
    },
    {
      age: "23",
      its: "30477394",
      name: "Shehrebanu bai Mulla Abbas bhai Rampurawala",
      gender: "Female",
    },
  ],
  [{ age: "50", its: "30315142", name: "Moiz Poonawala", gender: "Male" }],
  [
    {
      age: "50",
      its: "30449017",
      name: "Mulla Aziz bhai Shaikh Abdulqadir bhai Rampurawala",
      gender: "Male",
    },
    {
      age: "42",
      its: "30449019",
      name: "Tasneem bai Mulla Aziz bhai Rampurawala",
      gender: "Female",
    },
    { age: "19", its: "30449022", name: "Taher bhai Mulla Aziz bhai Rampurawala", gender: "Male" },
    { age: "15", its: "30913552", name: "Taha bhai Mulla Aziz bhai Rampurawala", gender: "Male" },
  ],
  [
    { age: "48", its: "30919543", name: "Fakhruddin bhai Abbasali bhai Khandwala", gender: "Male" },
    { age: "65", its: "40448224", name: "Fatema bai Abbasali bhai Khandwala", gender: "Female" },
    { age: "41", its: "40448225", name: "Zainab bai Fakhruddin bhai Khandwala", gender: "Female" },
    { age: "13", its: "60446635", name: "Yusuf bhai Fakhruddin bhai Khandwala", gender: "Male" },
    { age: "15", its: "60481548", name: "Nisreen bai Fakhruddin bhai Khandwala", gender: "Female" },
    { age: "19", its: "60481549", name: "Sakina bai Fakhruddin bhai Khandwala", gender: "Female" },
  ],
  [
    { age: "70", its: "20432051", name: "Mansoor bhai Taher bhai Suttarwala", gender: "Male" },
    { age: "55", its: "30443500", name: "Salma bai Mansoor bhai Suttarwala", gender: "Female" },
    { age: "35", its: "30494800", name: "Fatema bai Husain bhai Bohari", gender: "Female" },
    { age: "7", its: "40162645", name: "Mustafa bhai Husain bhai Bohari", gender: "Male" },
    { age: "38", its: "60423652", name: "Husain bhai Jabir bhai Bohari", gender: "Male" },
  ],
  [
    { age: "44", its: "20326612", name: "Zoeb bhai Zakirhusain bhai Patrawala", gender: "Male" },
    { age: "43", its: "30707032", name: "Salma bai Zoeb bhai Patrawala", gender: "Female" },
    { age: "15", its: "40902259", name: "Insiyah bai Zoeb bhai Patrawala", gender: "Female" },
    { age: "40", its: "0", name: "Sugra", gender: "Female" },
    { age: "52", its: "0", name: "Murtaza", gender: "Female" },
  ],
  [
    {
      age: "38",
      its: "30407428",
      name: "Abbasali bhai Qutbuddin bhai Dongarpurwala",
      gender: "Male",
    },
    {
      age: "33",
      its: "30477654",
      name: "Sakina bai Abbasali bhai Dongarpurwala",
      gender: "Female",
    },
  ],
  [
    { age: "77", its: "20326984", name: "Husaini Bootwala", gender: "Male" },
    { age: "73", its: "0", name: "Sugra Bootwala", gender: "Female" },
  ],
  [
    { age: "12", its: "30117799", name: "Hatim bhai Mustafa bhai JAWARAWALA", gender: "Male" },
    { age: "10", its: "30151832", name: "Rashida bai Mustafa bhai JAWARAWALA", gender: "Female" },
    { age: "66", its: "50436269", name: "Zareena bai Shabbir bhai JAWARAWALA", gender: "Female" },
    { age: "38", its: "60461451", name: "Zainab bai Mustafa bhai JAWARAWALA", gender: "Female" },
  ],
  [
    { age: "83", its: "20341772", name: "Mehfooza bai Hatim bhai Radiowala", gender: "Female" },
    { age: "37", its: "30328862", name: "Arwa bai Moiz bhai Master", gender: "Female" },
    { age: "58", its: "30471786", name: "Nafisa bai Mulla Shabbir bhai Master", gender: "Female" },
    { age: "39", its: "30477777", name: "Moiz bhai Mulla Shabbir bhai Master", gender: "Male" },
    {
      age: "65",
      its: "30477786",
      name: "Mulla Shabbir bhai Shaikh Fakhruddin bhai Master",
      gender: "Male",
    },
    { age: "14", its: "40911479", name: "Aliasgar bhai Moiz bhai Master", gender: "Male" },
    { age: "11", its: "40920357", name: "Malekulashter bhai Moiz bhai Master", gender: "Male" },
    { age: "76", its: "0", name: "Nooruddin Master", gender: "Male" },
    { age: "70", its: "0", name: "Bilkis Master", gender: "Female" },
  ],
  [
    { age: "62", its: "20325913", name: "Moiz bhai Fazalehusain bhai Ansari", gender: "Male" },
    { age: "50", its: "30377836", name: "Farida bai Moiz bhai Ansari", gender: "Female" },
    { age: "30", its: "30377837", name: "Huzaifa bhai Moiz bhai Ansari", gender: "Male" },
    { age: "28", its: "30377838", name: "Aliasgar bhai Moiz bhai Ansari", gender: "Male" },
    { age: "24", its: "50487207", name: "Fatema bai Huzaifa bhai Ansari", gender: "Female" },
    { age: "25", its: "60412261", name: "Ruqaiyah bai Aliasgar bhai Ansari", gender: "Female" },
  ],
  [
    {
      age: "84",
      its: "20320053",
      name: "Shaikh Yusuf bhai Shaikh Abdullah bhai Shakir",
      gender: "Male",
    },
    { age: "73", its: "30384104", name: "Radiyah bai Shaikh Yusuf bhai Shakir", gender: "Female" },
    {
      age: "50",
      its: "30384106",
      name: "Mulla Mufaddal bhai Shaikh Yusuf bhai Zakir",
      gender: "Male",
    },
    { age: "45", its: "30384107", name: "Lulua bai Mulla Mufaddal bhai Zakir", gender: "Female" },
    { age: "19", its: "30805568", name: "Arwa bai Mulla Mufaddal bhai Zakir", gender: "Female" },
    { age: "16", its: "30805571", name: "Mohammed bhai Mulla Mufaddal bhai Zakir", gender: "Male" },
  ],
  [
    {
      age: "53",
      its: "50440502",
      name: "Aliasgar bhai Shaikh Fakhruddin bhai Kothawala",
      gender: "Male",
    },
    { age: "46", its: "50440503", name: "Tasneem bai Aliasgar bhai Kothawala", gender: "Female" },
    { age: "25", its: "50440504", name: "Mustafa bhai Aliasgar bhai Kothawala", gender: "Male" },
    { age: "16", its: "30919111", name: "Ruqayiyya Kothawala", gender: "Female" },
  ],
  [
    { age: "24", its: "30377766", name: "Sakina bai Murtaza bhai Barrister", gender: "Female" },
    { age: "1", its: "40232050", name: "Umme Salama bai Murtaza bhai Barrister", gender: "Female" },
    {
      age: "56",
      its: "40407069",
      name: "Ezzuddin bhai Shaikh Fakhruddin bhai Barrister",
      gender: "Male",
    },
    { age: "54", its: "40407070", name: "Rashida bai Ezzuddin bhai Barrister", gender: "Female" },
    { age: "29", its: "40407071", name: "Murtaza bhai Ezzuddin bhai Barrister", gender: "Male" },
    { age: "23", its: "40407072", name: "Naqiyah bai Ezzuddin bhai Barrister", gender: "Female" },
  ],
  [
    { age: "68", its: "20324921", name: "Shaikh Abid bhai Ishaqali bhai Husaini", gender: "Male" },
    { age: "8", its: "30160142", name: "Insiya bai Abdeali bhai husaini", gender: "Female" },
    { age: "68", its: "30369900", name: "Zakiya bai Shaikh Abid bhai Husaini", gender: "Female" },
    { age: "37", its: "30369903", name: "Abdeali bhai Shaikh Abid bhai Husaini", gender: "Male" },
    { age: "33", its: "30378899", name: "Arwa bai Abdeali bhai Husaini", gender: "Female" },
    { age: "5", its: "40153545", name: "Husaina bai Abdeali bhai Husaini", gender: "Female" },
    { age: "40", its: "3036709", name: "Taher Hussaini", gender: "Male" },
    { age: "27", its: "30369954", name: "Aliasgar Husaini ", gender: "Male" },
    { age: "48", its: "30369976", name: "Mubaraka Husaini", gender: "Female" },
    { age: "30", its: "40400221", name: "Zainab Taherbhai", gender: "Female" },
    { age: "75", its: "30369916", name: "Farida Husaini", gender: "Female" },
  ],
  [
    { age: "36", its: "30360752", name: "Zahabiyah bai Shaikh Moiz bhai Jinia", gender: "Female" },
    { age: "40", its: "30386655", name: "Shaikh Moiz bhai Shabbir bhai Jinia", gender: "Male" },
    { age: "5", its: "40180980", name: "Burhanuddin bhai Shaikh Moiz bhai Jinia", gender: "Male" },
  ],
  [
    { age: "63", its: "20326027", name: "Saifuddin bhai Abdulrasool bhai Aman", gender: "Male" },
    { age: "29", its: "30464711", name: "Tasneem bai Hatim bhai Aman", gender: "Female" },
    { age: "5", its: "40192936", name: "Burhanuddin bhai Hatim bhai Aman", gender: "Male" },
    { age: "56", its: "60461151", name: "Hameda bai Saifuddin bhai Aman", gender: "Female" },
    { age: "33", its: "60461152", name: "Hatim bhai Saifuddin bhai Aman", gender: "Male" },
  ],
  [
    { age: "27", its: "40420112", name: "Aliasgar Shakir", gender: "Male" },
    { age: "22", its: "40420113", name: "Zainab Shakir", gender: "Female" },
    { age: "25", its: "30390027", name: "Mohammad", gender: "Male" },
  ],
  [
    { age: "39", its: "30491676", name: "Murtaza bhai Asgarali bhai Lokhandwala", gender: "Male" },
    { age: "6", its: "40170317", name: "Rukaiya bai Murtaza bhai Lokhandwala", gender: "Female" },
    { age: "40", its: "40471228", name: "Rashida bai Murtaza bhai Lokhandwala", gender: "Female" },
    { age: "13", its: "40484595", name: "Aliasgar bhai Murtaza bhai Lokhandwala", gender: "Male" },
  ],
  [
    { age: "45", its: "30302508", name: "Yusuf bhai Moiz bhai Gittham", gender: "Male" },
    { age: "45", its: "30302510", name: "Razia bai Yusuf bhai Gittham", gender: "Female" },
    { age: "10", its: "40152084", name: "Saifuddin bhai Yusuf bhai Gittham", gender: "Male" },
    { age: "17", its: "40901994", name: "Zainab bai Yusuf bhai Gittham", gender: "Female" },
  ],
  [
    {
      age: "36",
      its: "30375894",
      name: "Munira bai Mulla Ismaeel bhai Adenwala",
      gender: "Female",
    },
    {
      age: "68",
      its: "30376922",
      name: "Shaikh Kutubkhan bhai Mulla Mohammed bhai Adenwala",
      gender: "Male",
    },
    {
      age: "62",
      its: "30376923",
      name: "Tasneem bai Shaikh Kutubkhan bhai Adenwala",
      gender: "Female",
    },
    {
      age: "38",
      its: "30376924",
      name: "Mulla Ismaeel bhai Shaikh Kutubkhan bhai Adenwala",
      gender: "Male",
    },
    { age: "14", its: "30914209", name: "Batul bai Mulla Ismaeel bhai Adenwala", gender: "Female" },
    {
      age: "11",
      its: "40919103",
      name: "Burhanuddin bhai Mulla Ismaeel bhai Adenwala",
      gender: "Male",
    },
  ],
  [
    {
      age: "28",
      its: "40466113",
      name: "Aliasgar bhai Shaikh Mohammedulbaqir bhai Nadir",
      gender: "Male",
    },
    {
      age: "58",
      its: "40466115",
      name: "Rashida bai Shaikh Mohammedulbaqir bhai Nadir",
      gender: "Female",
    },
    {
      age: "61",
      its: "40466116",
      name: "Shaikh Mohammedulbaqir bhai Shaikh Ismail bhai Nadir",
      gender: "Male",
    },
  ],
  [
    {
      age: "32",
      its: "40434002",
      name: "Shehrebanu bai Shabbir bhai Bagasrawala",
      gender: "Female",
    },
    {
      age: "13",
      its: "40909532",
      name: "Amatullah bai Shabbir bhai Bagasrawala",
      gender: "Female",
    },
    {
      age: "61",
      its: "60458592",
      name: "Munira bai Hakimuddin bhai Bagasrawala",
      gender: "Female",
    },
  ],
  [
    { age: "85", its: "20337235", name: "Abdulhusain bhai Abdulqadir bhai Sura", gender: "Male" },
    { age: "69", its: "30414776", name: "Rashida bai Abdulhusain bhai Sura", gender: "Female" },
  ],
  [
    {
      age: "43",
      its: "20435759",
      name: "Aliasgar bhai Shabbir bhai Darukhanawala",
      gender: "Male",
    },
    {
      age: "14",
      its: "50183030",
      name: "Shabbir bhai Aliasgar bhai Darukhanawala",
      gender: "Male",
    },
    {
      age: "19",
      its: "60446220",
      name: "Sakina bai Aliasgar bhai Darukhanawala",
      gender: "Female",
    },
    { age: "40", its: "60446221", name: "Ajab bai Aliasgar bhai Darukhanawala", gender: "Female" },
  ],
  [
    { age: "16", its: "30915872", name: "Mohammed bhai Abbas bhai Sukhsarwala", gender: "Male" },
    { age: "14", its: "40909521", name: "Mufaddal bhai Abbas bhai Sukhsarwala", gender: "Male" },
  ],
  [
    { age: "53", its: "20318347", name: "Jumana bai Ibrahim bhai Khumanpur", gender: "Female" },
    { age: "22", its: "30367054", name: "Insiyah bai Ibrahim bhai Khumanpur", gender: "Female" },
    { age: "19", its: "30368607", name: "Mohammed bhai Ibrahim bhai Khumanpur", gender: "Male" },
  ],
  [
    { age: "51", its: "30375951", name: "Taher bhai Fidahusain bhai Makati", gender: "Male" },
    { age: "20", its: "30375952", name: "Abdeali bhai Taher bhai Makati", gender: "Male" },
    { age: "51", its: "30375953", name: "Mubarakah bai Taher bhai Makati", gender: "Female" },
  ],
  [{ age: "23", its: "50442242", name: "Hussain Bahrainwala", gender: "Male" }],
  [
    {
      age: "62",
      its: "30308385",
      name: "Mulla Juzer bhai Mulla Mohammed bhai Adenwala",
      gender: "Male",
    },
    { age: "62", its: "30310335", name: "Nafisa bai Mulla Juzer bhai Adenwala", gender: "Female" },
  ],
  [
    { age: "17", its: "30703549", name: "Asma bai Taher bhai Madhwaswala", gender: "Female" },
    { age: "42", its: "50441104", name: "Sakina bai Taher bhai Madhwaswala", gender: "Female" },
    { age: "19", its: "50491300", name: "Abbas bhai Taher bhai Madhwaswala", gender: "Male" },
    { age: "12", its: "50491590", name: "Alefiyah bai Taher bhai Madhwaswala", gender: "Female" },
  ],
  [
    {
      age: "19",
      its: "30342136",
      name: "Burhanuddin bhai Khuzaima bhai Mithai wala",
      gender: "Male",
    },
    {
      age: "45",
      its: "30342627",
      name: "Khuzaima bhai Shaikh Shabbir bhai Mithaiwala",
      gender: "Male",
    },
  ],
  [
    {
      age: "58",
      its: "20352044",
      name: "Shaikh Habib bhai Shaikh Mohammedhusain bhai Badri",
      gender: "Male",
    },
    { age: "51", its: "30488084", name: "Farida bai Shaikh Habib bhai Badri", gender: "Female" },
  ],
  [{ age: "22", its: "30388840", name: "Mohammed bhai Husain bhai J.p.", gender: "Male" }],
  [
    { age: "54", its: "30913237", name: "Aliasgar bhai Maher bhai Mithiyawala", gender: "Male" },
    { age: "52", its: "40450550", name: "Nisreen bai Aliasgar bhai Mithiyawala", gender: "Female" },
    { age: "20", its: "40450551", name: "Sakina bai Aliasgar bhai Mithiyawala", gender: "Female" },
  ],
  [
    { age: "22", its: "30460172", name: "Taha bhai Qutbuddin bhai Dahodwala", gender: "Male" },
    { age: "20", its: "30460174", name: "Zahra bai Qutbuddin bhai Dahodwala", gender: "Female" },
  ],
  [
    {
      age: "68",
      its: "40407931",
      name: "Rashida bai Tasaddukhusain bhai Bugadwala",
      gender: "Female",
    },
  ],
  [{ age: "70", its: "30376258", name: "Jumana Arthunawala", gender: "Female" }],
  [
    {
      age: "59",
      its: "20315726",
      name: "Mulla Shabbir bhai Ibrahim bhai Madarwala",
      gender: "Male",
    },
    {
      age: "52",
      its: "30373345",
      name: "Batul bai Mulla Shabbir bhai Madarwala",
      gender: "Female",
    },
  ],
  [
    { age: "44", its: "30420223", name: "Alefiyah bai Kausar bhai Patanwala", gender: "Female" },
    { age: "16", its: "30914101", name: "Hakimuddin bhai Kausar bhai Patanwala", gender: "Male" },
    { age: "8", its: "50193471", name: "Rukaiyah bai Kausar bhai Patanwala", gender: "Female" },
  ],
  [{ age: "51", its: "30373559", name: "Huzaifa bhai Shaikh Shabbir bhai Ghia", gender: "Male" }],
  [
    {
      age: "74",
      its: "20326022",
      name: "Shabbir bhai Mulla Abdeali bhai Masalawala",
      gender: "Male",
    },
    { age: "64", its: "50436253", name: "Nafisa bai Shabbir bhai Masalawala", gender: "Female" },
  ],
  [{ age: "74", its: "20431318", name: "Mohammed bhai Asgarali bhai Karachiwala", gender: "Male" }],
  [{ age: "60", its: "20325920", name: "Saifuddin Phaltanwala", gender: "Male" }],
  [
    { age: "26", its: "30307061", name: "Mariyah bai Qusai bhai Matcheswala", gender: "Female" },
    { age: "55", its: "30373675", name: "Khadija bai Yusuf bhai Matcheswala", gender: "Female" },
    { age: "29", its: "30705381", name: "Qusai bhai Yusuf bhai Matcheswala", gender: "Male" },
  ],
  [
    { age: "57", its: "40439438", name: "Abbas bhai Mohsin bhai Tajani", gender: "Male" },
    { age: "50", its: "40439439", name: "Shameem bai Abbas bhai Tajani", gender: "Female" },
    { age: "21", its: "40439441", name: "Murtaza bhai Abbas bhai Tajani", gender: "Male" },
  ],
  [
    {
      age: "71",
      its: "20322244",
      name: "Shaikh Jabirhusain bhai Mulla Abdullah bhai Burhani",
      gender: "Male",
    },
    {
      age: "71",
      its: "30387466",
      name: "Farida bai Shaikh Jabirhusain bhai Burhani",
      gender: "Female",
    },
    { age: "30", its: "40800006", name: "Ummesalma Burhani", gender: "Female" },
    { age: "30", its: "40902221", name: "Qusai Burhani", gender: "Male" },
  ],
  [
    { age: "26", its: "30477392", name: "Sakina bai Shabbir bhai Bawaji", gender: "Female" },
    { age: "29", its: "30487425", name: "Shabbir bhai Nuruddin bhai Bawaji", gender: "Male" },
    { age: "17", its: "40800028", name: "Taher bhai Nuruddin bhai Bawaji", gender: "Male" },
  ],
  [
    {
      age: "76",
      its: "20431451",
      name: "Shaikh Mohammed bhai Fazalehusain bhai Dhariwala",
      gender: "Male",
    },
    { age: "11", its: "30115091", name: "Burhanuddin bhai Murtaza bhai Dhariwala", gender: "Male" },
    { age: "9", its: "30151880", name: "Mufaddal bhai Murtaza bhai Dhariwala", gender: "Male" },
    { age: "35", its: "30369451", name: "Zainab bai Murtaza bhai Dhariwala", gender: "Female" },
    { age: "16", its: "30920298", name: "Idris bhai Quraish bhai Dhariwala", gender: "Male" },
    {
      age: "71",
      its: "60458543",
      name: "Nafisa bai Shaikh Mohammed bhai Dhariwala",
      gender: "Female",
    },
    { age: "43", its: "60458545", name: "Sakina bai Quraish bhai Dhariwala", gender: "Female" },
  ],
  [
    {
      age: "85",
      its: "30373030",
      name: "Zahra bai Shaikh Akberali bhai Patanwala",
      gender: "Female",
    },
    {
      age: "43",
      its: "30373093",
      name: "Tasneem bai Mulla Aliasgar bhai Patanwala",
      gender: "Female",
    },
    {
      age: "49",
      its: "30373095",
      name: "Mulla Aliasgar bhai Shaikh Akberali bhai Patanwala",
      gender: "Male",
    },
    {
      age: "21",
      its: "30373118",
      name: "Murtaza bhai Mulla Aliasgar bhai Patanwala",
      gender: "Male",
    },
    {
      age: "18",
      its: "30705347",
      name: "Jamila bai Mulla Aliasgar bhai Patanwala",
      gender: "Female",
    },
  ],
  [
    { age: "18", its: "30708498", name: "Abbas Gojipurwala", gender: "Male" },
    { age: "40", its: "40451556", name: "Mohammed Petladwala", gender: "Male" },
    { age: "32", its: "40410027", name: "Zaineb Petladwala", gender: "Female" },
    { age: "35", its: "50508377", name: "Fatema Jhabuawala", gender: "Female" },
    { age: "13", its: "40917850", name: "Murtaza Jhabuawala", gender: "Female" },
    { age: "38", its: "50435506", name: "Huzefa Jhabuawala", gender: "Male" },
    { age: "55", its: "20325926", name: "Shabbir Jitpurwala", gender: "Male" },
    { age: "25", its: "30377880", name: "Taha Jitpurwala", gender: "Male" },
    { age: "55", its: "20326037", name: "Aziz Babat", gender: "Male" },
  ],
  [
    { age: "38", its: "60436413", name: "Alefiya Electricwala", gender: "Female" },
    { age: "42", its: "60436413", name: "Aliasgar Electricwala", gender: "Male" },
    { age: "12", its: "30152987", name: "Hatim Electricwala", gender: "Male" },
  ],
  [
    { age: "25", its: "40432888", name: "Farida bai Husain bhai Badri", gender: "Female" },
    { age: "31", its: "40482323", name: "Husain bhai Wahid bhai Badri", gender: "Male" },
  ],
  [
    { age: "8", its: "30153533", name: "Zahra bai Husain bhai Razee", gender: "Female" },
    { age: "59", its: "30384219", name: "Ruqaiyah bai Shaikh Hatim bhai Razee", gender: "Female" },
    { age: "37", its: "30384220", name: "Husain bhai Shaikh Hatim bhai Razee", gender: "Male" },
    { age: "31", its: "40401356", name: "Zainab bai Husain bhai Razee", gender: "Female" },
    { age: "66", its: "20320097", name: "Shk Hatim Razee", gender: "Male" },
    { age: "32", its: "30384221", name: "Ibrahim Razee", gender: "Male" },
  ],
  [{ age: "75", its: "30373411", name: "Maleka bai Hatim bhai Dholkawala", gender: "Female" }],
  [
    { age: "63", its: "20325968", name: "Juzer bhai Mansur bhai Kasubhai", gender: "Male" },
    { age: "55", its: "50466131", name: "Yasmeen bai Juzer bhai Kasubhai", gender: "Female" },
  ],
  [
    { age: "55", its: "20326557", name: "Munira bai Mustafa bhai Patanwala", gender: "Female" },
    { age: "30", its: "30377444", name: "Murtaza bhai Mustafa bhai Patanwala", gender: "Male" },
    { age: "25", its: "30377445", name: "Husain bhai Mustafa bhai Patanwala", gender: "Male" },
  ],
  [
    { age: "59", its: "20326545", name: "Mansoor bhai Shaikh Taher bhai Nasir", gender: "Male" },
    { age: "43", its: "30377397", name: "Tasneem bai Mansoor bhai Nasir", gender: "Female" },
    { age: "18", its: "30709026", name: "Alefiyah bai Mansoor bhai Nasir", gender: "Female" },
    { age: "14", its: "40903684", name: "Ibrahim bhai Mansoor bhai Nasir", gender: "Male" },
  ],
  [
    { age: "78", its: "20326186", name: "Rashida Khadkiwala", gender: "Female" },
    { age: "45", its: "30373013", name: "Yusuf Hamid", gender: "Male" },
    { age: "39", its: "40407201", name: "Zainab Hamid", gender: "Female" },
    { age: "17", its: "30705459", name: "Sakina Hamid", gender: "Female" },
    { age: "9", its: "30151847", name: "Samina hamid", gender: "Female" },
  ],
  [
    {
      age: "72",
      its: "20325852",
      name: "Shaikh Yusuf bhai Mulla Qadirali bhai Shakir",
      gender: "Male",
    },
    {
      age: "60",
      its: "30377151",
      name: "Mulla Tasneem bai Shaikh Yusuf bhai Shakir",
      gender: "Female",
    },
    { age: "18", its: "40800837", name: "Husain bhai Mulla Abizer bhai Saifee", gender: "Male" },
  ],
  [
    { age: "53", its: "30903898", name: "Mulla Firoz bhai Ali bhai Ghadiyali", gender: "Male" },
    { age: "49", its: "30903899", name: "Ajab bai Mulla Firoz bhai Ghadiyali", gender: "Female" },
    { age: "19", its: "30903901", name: "Munira bai Mulla Firoz bhai Ghadiyali", gender: "Female" },
    { age: "60", its: "20328166", name: "Amtuzzehra Moga", gender: "Female" },
  ],
  [
    {
      age: "66",
      its: "20326525",
      name: "Najmuddin bhai Mohammedhusain bhai Kapasi",
      gender: "Male",
    },
    { age: "63", its: "50436255", name: "Shireen bai Najmuddin bhai Kapasi", gender: "Female" },
  ],
  [
    { age: "42", its: "40407660", name: "Zainab Modi", gender: "Female" },
    { age: "19", its: "40900531", name: "Khadija Modi", gender: "Female" },
    { age: "12", its: "40914667", name: "Amatullah Modi", gender: "Female" },
  ],
  [
    { age: "83", its: "20316704", name: "Sakina bai Abid bhai Hardawala", gender: "Female" },
    { age: "58", its: "30401201", name: "Mustafa bhai Abid bhai Hardawala", gender: "Male" },
    { age: "49", its: "30401202", name: "Tasneem bai Mustafa bhai Hardawala", gender: "Female" },
  ],
  [
    { age: "29", its: "50407406", name: "Alefiyah bai Husain bhai Poonawala", gender: "Female" },
    { age: "50", its: "60461307", name: "Jumana bai Huzaifa bhai Poonawala", gender: "Female" },
    { age: "28", its: "60461308", name: "Husain bhai Huzaifa bhai Poonawala", gender: "Male" },
    { age: "21", its: "60461309", name: "Burhanuddin bhai Huzaifa bhai Poonawala", gender: "Male" },
  ],
  [
    { age: "51", its: "20325820", name: "Yusuf bhai Fazalehusain bhai Dewaswala", gender: "Male" },
    { age: "21", its: "30377665", name: "Ibrahim bhai Yusuf bhai Dewaswala", gender: "Male" },
  ],
  [
    { age: "31", its: "30341142", name: "Ajab bai Mulla Mohsin bhai Shakir", gender: "Female" },
    {
      age: "33",
      its: "30360052",
      name: "Mulla Mohsin bhai Shaikh Khuzaima bhai Shakir",
      gender: "Male",
    },
  ],
  [
    { age: "32", its: "50448546", name: "Nafisa Saifee", gender: "Female" },
    { age: "8", its: "40173304", name: "Zahra Saifee", gender: "Female" },
  ],
  [
    { age: "74", its: "20326778", name: "Abdeali bhai Roshanali bhai Daruwala", gender: "Male" },
    { age: "65", its: "30375270", name: "Jamila bai Abdeali bhai Daruwala", gender: "Female" },
  ],
  [
    {
      age: "60",
      its: "50436202",
      name: "Mulla Saifuddin bhai Zoeb bhai Habibulla",
      gender: "Male",
    },
    {
      age: "55",
      its: "50436203",
      name: "Munira bai Mulla Saifuddin bhai Habibulla",
      gender: "Female",
    },
    {
      age: "23",
      its: "50436205",
      name: "Zainab bai Mulla Saifuddin bhai Habibulla",
      gender: "Female",
    },
    { age: "20", its: "30920207", name: "Farah Electricwala", gender: "Female" },
  ],
  [
    {
      age: "18",
      its: "30708921",
      name: "Mariyah bai Nooruddin bhai Bhinderwala",
      gender: "Female",
    },
    { age: "49", its: "30803328", name: "Umaima bai Nooruddin bhai Bhinderwala", gender: "Female" },
    {
      age: "51",
      its: "40407371",
      name: "Nooruddin bhai Shaikh Fakhruddin bhai Bhinderwala",
      gender: "Male",
    },
    { age: "22", its: "40407692", name: "Moiz bhai Nooruddin bhai Bhinderwala", gender: "Male" },
  ],
  [{ age: "63", its: "30601180", name: "Durriya bai Moiz bhai Bhiwandiwala", gender: "Female" }],
  [
    { age: "23", its: "30432573", name: "Rashida Shk Shabbir", gender: "Female" },
    { age: "18", its: "30700039", name: "Abdulqader Shk Shabbirbhai", gender: "Male" },
  ],
  [
    { age: "4", its: "50202786", name: "Ruqaiyah bai Mustafa bhai Nalwala", gender: "Female" },
    { age: "32", its: "60402744", name: "Mariyah bai Mustafa bhai Nalwala", gender: "Female" },
    { age: "38", its: "60461515", name: "Mustafa bhai Badruddin bhai Nalwala", gender: "Male" },
    { age: "65", its: "60461516", name: "Munira bai Badruddin bhai Nalwala", gender: "Female" },
  ],
  [
    { age: "33", its: "40474019", name: "Mohammad bhai Abbas bhai Vohra", gender: "Male" },
    { age: "33", its: "60461263", name: "Tasneem bai Mohammad bhai Vohra", gender: "Female" },
  ],
  [
    { age: "23", its: "30396129", name: "Zainab Shabbir", gender: "Female" },
    { age: "20", its: "30396542", name: "Zainab Kuwawala", gender: "Female" },
    { age: "20", its: "60433163", name: "Sakina Ezzy", gender: "Female" },
  ],
  [
    { age: "45", its: "30374415", name: "Fatema bai Husain bhai Ringnodwala", gender: "Female" },
    { age: "47", its: "30374416", name: "Husain bhai Asgarali bhai Ringnodwala", gender: "Male" },
    { age: "20", its: "30374417", name: "Tasneem bai Murtaza bhai Baugwala", gender: "Female" },
    { age: "17", its: "40800217", name: "Taha bhai Husain bhai Ringnodwala", gender: "Male" },
  ],
  [
    { age: "40", its: "30375317", name: "Khadija bai Murtaza bhai Bootwala", gender: "Female" },
    { age: "48", its: "30708929", name: "Murtaza bhai Taher bhai Bootwala", gender: "Male" },
    { age: "14", its: "40910529", name: "Burhanuddin bhai Murtaza bhai Bootwala", gender: "Male" },
  ],
  [
    { age: "47", its: "30375773", name: "Mustafa Emadi", gender: "Male" },
    { age: "42", its: "30375775", name: "Zainab Emadi", gender: "Female" },
    { age: "14", its: "40910524", name: "Aliasgar Emadi", gender: "Male" },
  ],
  [{ age: "76", its: "20326461", name: "Mansoor bhai Abdeali bhai Lokhandwala", gender: "Male" }],
  [
    { age: "47", its: "30338755", name: "Mufaddal bhai Shaikh Mohammed bhai Mama", gender: "Male" },
    { age: "42", its: "30338756", name: "Sakina bai Mufaddal bhai Mama", gender: "Female" },
    { age: "18", its: "30338951", name: "Adnan bhai Mufaddal bhai Mama", gender: "Male" },
    { age: "12", its: "40914205", name: "Ibrahim bhai Mufaddal bhai Mama", gender: "Male" },
  ],
  [
    { age: "46", its: "30461054", name: "Sakina bai Moayyad bhai Hilal", gender: "Female" },
    { age: "18", its: "30923901", name: "Zainab bai Moayyad bhai Hilal", gender: "Female" },
  ],
  [
    {
      age: "64",
      its: "20325849",
      name: "Fakhruddin bhai Alihusain bhai Sarodawala",
      gender: "Male",
    },
    { age: "54", its: "30377680", name: "Fatema bai Fakhruddin bhai Sarodawala", gender: "Female" },
    { age: "25", its: "60481354", name: "Mohammed Antriwala", gender: "Male" },
  ],
  [
    { age: "47", its: "50442824", name: "Insiyah bai Juzer bhai Nandervawala", gender: "Female" },
    { age: "23", its: "50442825", name: "Ummesalma bai Juzer bhai Nandervawala", gender: "Female" },
    { age: "20", its: "50491478", name: "Mustafa bhai Juzer bhai Nandervawala", gender: "Male" },
  ],
  [
    {
      age: "36",
      its: "30397078",
      name: "Juzerali bhai Mulla Zoherali bhai Bundiwala",
      gender: "Male",
    },
    { age: "33", its: "30438693", name: "Tasneem bai Juzerali bhai Bundiwala", gender: "Female" },
  ],
  [
    { age: "47", its: "30375782", name: "Lubaina bai Adnan bhai Pedhiwala", gender: "Female" },
    {
      age: "47",
      its: "30375783",
      name: "Adnan bhai Mulla Zakirhusain bhai Pedhiwala",
      gender: "Male",
    },
    { age: "17", its: "40800169", name: "Khadija bai Adnan bhai Pedhiwala", gender: "Female" },
    { age: "15", its: "40800171", name: "Abizer bhai Adnan bhai Pedhiwala", gender: "Male" },
    { age: "19", its: "40900398", name: "Zainab bai Adnan bhai Pedhiwala", gender: "Female" },
    { age: "58", its: "30374405", name: "Tasneem Sh Mustafa Ezzy", gender: "Female" },
    { age: "60", its: "30374406", name: "Sh Mustafa Ezzy", gender: "Male" },
  ],
  [
    { age: "58", its: "30375911", name: "Farida bai Qutbuddin bhai Farid", gender: "Female" },
    { age: "61", its: "30705464", name: "Qutbuddin bhai Ghulamali bhai Farid", gender: "Male" },
  ],
  [
    { age: "46", its: "20405816", name: "Yusuf bhai Abbas bhai Sunelwala", gender: "Male" },
    { age: "11", its: "30117784", name: "Mariya bai Yusuf bhai Sunelwala", gender: "Female" },
    { age: "37", its: "30494019", name: "Alefiyah bai Yusuf bhai Sunelwala", gender: "Female" },
    { age: "8", its: "40172673", name: "Burhanuddin bhai Yusuf bhai Sunelwala", gender: "Male" },
    { age: "14", its: "50464640", name: "Shabbir bhai Yusuf bhai Sunailwala", gender: "Male" },
  ],
  [{ age: "57", its: "30373996", name: "Mustafa bhai Abdeali bhai Motiwala", gender: "Male" }],
  [
    { age: "53", its: "30373648", name: "Mariyah bai Imran bhai Rangwala", gender: "Female" },
    { age: "22", its: "30373649", name: "Mohammed bhai Juzer bhai Sardharwala", gender: "Male" },
  ],
  [
    { age: "15", its: "30905160", name: "Hasnain bhai Murtaza bhai Partapurwala", gender: "Male" },
    {
      age: "42",
      its: "40462030",
      name: "Mahjabeen bai Murtaza bhai Partapurwala",
      gender: "Female",
    },
    {
      age: "45",
      its: "60461118",
      name: "Murtaza bhai Sajjadhusain bhai Partapurwala",
      gender: "Male",
    },
  ],
  [
    { age: "61", its: "30306009", name: "Maryam bai Qayumali bhai Morbiwala", gender: "Female" },
    { age: "70", its: "30306010", name: "Qayumali bhai Taiyebali bhai Morbiwala", gender: "Male" },
    { age: "29", its: "30306012", name: "Murtaza bhai Qayumali bhai Morbiwala", gender: "Male" },
  ],
  [
    {
      age: "9",
      its: "30151900",
      name: "Burhanuddin bhai Shabbir bhai Fatepurwala",
      gender: "Male",
    },
    { age: "35", its: "50442867", name: "Insiya bai Shabbir bhai Fatepurwala", gender: "Female" },
    { age: "15", its: "50492621", name: "Zainab bai Shabbir bhai Fatepurwala", gender: "Female" },
  ],
  [
    {
      age: "59",
      its: "20325418",
      name: "Shaikh Shabbirhusain bhai Mulla Abbasali bhai Fatehnagri",
      gender: "Male",
    },
  ],
  [
    {
      age: "67",
      its: "20431313",
      name: "Mulla Murtaza bhai Mohammadhussain bhai Burhanpurwala",
      gender: "Male",
    },
    {
      age: "61",
      its: "60422881",
      name: "Shireen bai Mulla Murtaza bhai Burhanpurwala",
      gender: "Female",
    },
    {
      age: "37",
      its: "60422882",
      name: "Moiz bhai Mulla Murtaza bhai Burhanpurwala",
      gender: "Male",
    },
    {
      age: "31",
      its: "60422883",
      name: "Hasan bhai Mulla Murtaza bhai Burhanpurwala",
      gender: "Male",
    },
  ],
  [
    { age: "50", its: "20334050", name: "Husain bhai Sulaiman bhai Lokhandwala", gender: "Male" },
    { age: "22", its: "30423597", name: "Taher bhai Husain bhai Lokhandwala", gender: "Male" },
    { age: "43", its: "30423607", name: "Mubarakah bai Husain bhai Lokhandwala", gender: "Female" },
    { age: "24", its: "30423608", name: "Huzaifa bhai Husain bhai Lokhandwala", gender: "Male" },
  ],
  [
    { age: "75", its: "20325737", name: "Abbas bhai Nomanali bhai Polishwala", gender: "Male" },
    { age: "35", its: "30376141", name: "Husain bhai Abbas bhai Polishwala", gender: "Male" },
    { age: "35", its: "30427940", name: "Fatema bai Husain bhai Polishwala", gender: "Female" },
    { age: "11", its: "40917116", name: "Juzer bhai Husain bhai Polishwala", gender: "Male" },
  ],
  [
    { age: "33", its: "60440318", name: "Yasmeen Hasan", gender: "Female" },
    { age: "62", its: "60440316", name: "Shaheen Hasan", gender: "Female" },
  ],
  [{ age: "27", its: "30436312", name: "Idria Dawaiwala", gender: "Male" }],
  [
    {
      age: "71",
      its: "20326040",
      name: "Shaikh Shabbir bhai Zainulabedeen bhai Kagalwala",
      gender: "Male",
    },
    { age: "37", its: "30476871", name: "Jumana bai Moiz bhai Kagalwala", gender: "Female" },
    { age: "5", its: "40183844", name: "Zahra bai Moiz bhai Kagalwala", gender: "Female" },
    {
      age: "64",
      its: "40434805",
      name: "Nafisa bai Shaikh Shabbir bhai Kagalwala",
      gender: "Female",
    },
    { age: "42", its: "40434806", name: "Moiz bhai Shaikh Shabbir bhai Kagalwala", gender: "Male" },
    { age: "12", its: "40910528", name: "Hatim bhai Moiz bhai Kagalwala", gender: "Male" },
  ],
  [
    { age: "38", its: "30307117", name: "Durriya bai Ammar bhai Hamid", gender: "Female" },
    { age: "39", its: "30307561", name: "Ammar bhai Aliasgar bhai Hamid", gender: "Male" },
    { age: "14", its: "30906305", name: "Jumana bai Ammar bhai Hamid", gender: "Female" },
    { age: "8", its: "40156259", name: "Taha bhai Ammar bhai Hamid", gender: "Male" },
    { age: "70", its: "20302231", name: "Aliasgar Hamid", gender: "Male" },
    { age: "67", its: "30307559", name: "Maimuna Hamid", gender: "Female" },
  ],
  [
    { age: "33", its: "30394593", name: "Alefiyah bai Murtaza bhai Mushki", gender: "Female" },
    { age: "8", its: "40162835", name: "Idris bhai Murtaza bhai Mushki", gender: "Male" },
    {
      age: "37",
      its: "60461158",
      name: "Murtaza bhai Shaikh Sharafali bhai Mushki",
      gender: "Male",
    },
  ],
  [
    { age: "24", its: "50478762", name: "Mohammad Cyclewala", gender: "Male" },
    { age: "25", its: "40467231", name: "Taher Dabir", gender: "Male" },
  ],
  [
    { age: "41", its: "30376521", name: "M. Abdulqadir Sanjeliwala", gender: "Male" },
    { age: "40", its: "30373651", name: "Maria Sanjeliwala", gender: "Female" },
    { age: "16", its: "40900386", name: "Muffadal Sanjeliwala", gender: "Male" },
    { age: "14", its: "40907105", name: "Jamila Sanjeliwala", gender: "Female" },
    { age: "10", its: "40919038", name: "Mohammed Sanjeliwala", gender: "Male" },
  ],
  [
    { age: "71", its: "20325549", name: "Abbas bhai Fidahusain bhai Khadkiwala", gender: "Male" },
    { age: "55", its: "30375597", name: "Rehana bai Abbas bhai Khadkiwala", gender: "Female" },
  ],
  [
    { age: "53", its: "30377457", name: "Mulla Abizer bhai Abbas bhai Merchant", gender: "Male" },
    {
      age: "48",
      its: "30377458",
      name: "Rashida bai Mulla Abizer bhai Merchant",
      gender: "Female",
    },
    {
      age: "22",
      its: "30377460",
      name: "Burhanuddin bhai Mulla Abizer bhai Merchant",
      gender: "Male",
    },
    { age: "15", its: "30912674", name: "Husain bhai Fakhruddin bhai Morawala", gender: "Male" },
  ],
  [
    {
      age: "27",
      its: "50407435",
      name: "Abizer bhai Mulla Shabbir bhai Electricwala",
      gender: "Male",
    },
    { age: "50", its: "50407437", name: "Tasneem Poonawala", gender: "Female" },
  ],
  [
    { age: "26", its: "30375378", name: "Munira bai Taher bhai Hirani", gender: "Female" },
    { age: "25", its: "30413628", name: "Alefiyah bai Mufaddal bhai Hirani", gender: "Female" },
    { age: "28", its: "30435668", name: "Zainab bai Aliasgar bhai Hirani", gender: "Female" },
    { age: "30", its: "30438274", name: "Aliasgar bhai Firoz bhai Hirani", gender: "Male" },
    { age: "31", its: "50467755", name: "Taher bhai Firoz bhai Hirani", gender: "Male" },
    { age: "25", its: "50467756", name: "Mufaddal bhai Firoz bhai Hirani", gender: "Male" },
    { age: "52", its: "50467757", name: "Munira bai Firoz bhai Hirani", gender: "Female" },
    { age: "58", its: "50467798", name: "Firoz Hirani", gender: "Male" },
    { age: "21", its: "50467758", name: "Hatim Hirani", gender: "Male" },
  ],
  [
    {
      age: "89",
      its: "20326502",
      name: "Shaikh Mustansir bhai Mohsin bhai Shipchandler",
      gender: "Male",
    },
    { age: "43", its: "30384105", name: "Mariyah bai Murtaza bhai Shipchandler", gender: "Female" },
    {
      age: "87",
      its: "60461201",
      name: "Ruqaiyah bai Shaikh Mustansir bhai Shipchandler",
      gender: "Female",
    },
    {
      age: "51",
      its: "60461202",
      name: "Murtaza bhai Shaikh Mustansir bhai Shipchandler",
      gender: "Male",
    },
  ],
  [
    {
      age: "51",
      its: "20444938",
      name: "Aqeel bhai Shaikh Najmuddin bhai Baghdadwala",
      gender: "Male",
    },
    { age: "45", its: "30385059", name: "Fatema bai Aqeel bhai Baghdadwala", gender: "Female" },
    { age: "19", its: "30900414", name: "Khadija bai Aqeel bhai Baghdadwala", gender: "Female" },
    { age: "14", its: "40911459", name: "Naqiyah bai Aqeel bhai Baghdadwala", gender: "Female" },
  ],
  [
    { age: "61", its: "20406257", name: "Raj bhai Abid bhai Fatepurwala", gender: "Male" },
    { age: "55", its: "30709210", name: "Fatema bai Raj bhai Fatepurwala", gender: "Female" },
  ],
  [
    { age: "53", its: "20326571", name: "Shabbir bhai Taher bhai Kapadia", gender: "Male" },
    { age: "48", its: "30377796", name: "Nafisa bai Shabbir bhai Kapadia", gender: "Female" },
    { age: "19", its: "30701031", name: "Naqiyah bai Shabbir bhai Kapadia", gender: "Female" },
  ],
  [{ age: "56", its: "30600775", name: "Shabbir bhai Mohsin bhai Arsiwala", gender: "Male" }],
  [
    { age: "32", its: "60460628", name: "Arva Ben Bodeliwala", gender: "Female" },
    { age: "85", its: "60463369", name: "Rubab Ben Gojipurwala", gender: "Female" },
  ],
  [
    { age: "44", its: "20389999", name: "Aliasgar bhai Husain bhai Bahrainwala", gender: "Male" },
    { age: "72", its: "30375888", name: "Khadija bai Husain bhai Bahrainwala", gender: "Female" },
    { age: "38", its: "40407408", name: "Farida bai Aliasgar bhai Bahrainwala", gender: "Female" },
    { age: "12", its: "40914282", name: "Zainab bai Aliasgar bhai Bahrainwala", gender: "Female" },
    { age: "16", its: "50496607", name: "Sakina bai Aliasgar bhai Bahrainwala", gender: "Female" },
  ],
  [
    { age: "63", its: "20349932", name: "Yunus bhai Turabali bhai Tailor", gender: "Male" },
    { age: "56", its: "30459048", name: "Nafisa bai Yunus bhai Tailor", gender: "Female" },
  ],
  [
    { age: "51", its: "30369497", name: "Lubaina bai Shoeb bhai Indonesiawala", gender: "Female" },
    {
      age: "58",
      its: "30376200",
      name: "Shoeb bhai Fakhruddin bhai Indonesiawala",
      gender: "Male",
    },
  ],
  [
    {
      age: "55",
      its: "20326264",
      name: "Qutbuddin bhai Shaikh Fakhruddin bhai Bhinderwala",
      gender: "Male",
    },
    {
      age: "18",
      its: "30708924",
      name: "Mubarakah bai Qutbuddin bhai Bhinderwala",
      gender: "Female",
    },
    {
      age: "47",
      its: "40407689",
      name: "Mariyah bai Qutbuddin bhai Bhinderwala",
      gender: "Female",
    },
    { age: "22", its: "40407690", name: "Fatema bai Qutbuddin bhai Bhinderwala", gender: "Female" },
  ],
  [
    { age: "59", its: "30377786", name: "Mohammed bhai Nooruddin bhai Rajkotwala", gender: "Male" },
    { age: "50", its: "30377787", name: "Alefiyah bai Mohammed bhai Rajkotwala", gender: "Female" },
    {
      age: "73",
      its: "30377791",
      name: "Shakera bai Shaikh Aziz bhai Karmalawala",
      gender: "Female",
    },
    { age: "22", its: "1", name: "Burhanuddin Rajkotwala", gender: "Male" },
  ],
  [
    { age: "30", its: "30475841", name: "Abbas Haryanawala", gender: "Male" },
    { age: "27", its: "0", name: "Mustafa Paatwala", gender: "Male" },
    { age: "27", its: "0", name: "Murtaza Arab", gender: "Male" },
    { age: "29", its: "0", name: "Hussain Paatwala", gender: "Male" },
    { age: "29", its: "0", name: "Hussain Bohra", gender: "Male" },
    { age: "26", its: "0", name: "Burhanuddin Bohra", gender: "Male" },
    { age: "20", its: "0", name: "Abbas Chandarpur", gender: "Male" },
  ],
  [
    { age: "25", its: "50487130", name: "Fatema bai Burhanuddin bhai Kolsawala", gender: "Female" },
    {
      age: "25",
      its: "50491409",
      name: "Burhanuddin bhai Aliasgar bhai Kolsawala",
      gender: "Male",
    },
  ],
  [
    { age: "46", its: "20318772", name: "Yakuta", gender: "Female" },
    { age: "26", its: "30368174", name: "Sakina", gender: "Female" },
    { age: "22", its: "30368175", name: "Hatim", gender: "Female" },
    { age: "18", its: "30704176", name: "Fatena", gender: "Female" },
  ],
  [
    { age: "30", its: "30321281", name: "Ammar bhai Mulla Khuzaima bhai Joher", gender: "Male" },
    { age: "20", its: "30304991", name: "Fatema Joher", gender: "Female" },
  ],
  [
    { age: "41", its: "30374339", name: "Amena bai Murtaza bhai Rangwala", gender: "Female" },
    { age: "18", its: "30709144", name: "Jamila bai Murtaza bhai Rangwala", gender: "Female" },
    { age: "13", its: "40910523", name: "Mufaddal bhai Murtaza bhai Rangwala", gender: "Male" },
  ],
  [
    {
      age: "76",
      its: "30375966",
      name: "Najma bai Aijazhusain bhai Aurangabadwala",
      gender: "Female",
    },
  ],
  [
    { age: "23", its: "30393732", name: "Hussain Naharpurwala", gender: "Male" },
    { age: "18", its: "60415323", name: "Abdud Gorji", gender: "Male" },
    { age: "23", its: "60444358", name: "Mustufa Tinwala", gender: "Male" },
    { age: "20", its: "30452408", name: "Hatim Talwara", gender: "Male" },
  ],
  [
    { age: "54", its: "20325405", name: "Mustafa bhai Alihusain bhai Dilawar", gender: "Male" },
    { age: "49", its: "30377220", name: "Arwa bai Mustafa bhai Dilawar", gender: "Female" },
    { age: "26", its: "30377221", name: "Mohammed bhai Mustafa bhai Dilawar", gender: "Male" },
    { age: "26", its: "30377461", name: "Mariyah bai Mohammed bhai Dilawar", gender: "Female" },
  ],
  [{ age: "49", its: "50457410", name: "Munira bai Saifuddin bhai Kachwala", gender: "Female" }],
  [
    { age: "10", its: "30117787", name: "Murtaza bhai Mustafa bhai Penwala", gender: "Male" },
    { age: "66", its: "30309073", name: "Razia bai Ismail bhai Kapasi", gender: "Female" },
    { age: "71", its: "30408824", name: "Shakir bhai Mulla Abbas bhai Kapasi", gender: "Male" },
    { age: "58", its: "30408825", name: "Alefiyah bai Salman bhai Penwala", gender: "Female" },
    { age: "63", its: "30408833", name: "Fazela bai Shakir bhai Kapasi", gender: "Female" },
    { age: "39", its: "30408834", name: "Mustafa bhai Salman bhai Penwala", gender: "Male" },
    { age: "36", its: "30408835", name: "Nooruddin bhai Shakir bhai Kapasi", gender: "Male" },
    { age: "75", its: "30408854", name: "Ismail bhai Mulla Abbas bhai Kapasi", gender: "Male" },
    { age: "64", its: "30408855", name: "Salman bhai Mulla Abbas bhai Penwala", gender: "Male" },
    { age: "32", its: "50472869", name: "Zainab bai Mustafa bhai Penwala", gender: "Female" },
    { age: "33", its: "60439404", name: "Ummehani bai Nooruddin bhai Kapasi", gender: "Female" },
  ],
  [
    { age: "62", its: "60424489", name: "Murtaza Mankda", gender: "Male" },
    { age: "47", its: "60417455", name: "Nisreen Murtaza Mankda", gender: "Female" },
  ],
  [
    { age: "33", its: "30376615", name: "Tasneem bai Huzaifa bhai Kathawala", gender: "Female" },
    { age: "6", its: "40173270", name: "Zahra bai Huzaifa bhai Kathawala", gender: "Female" },
    {
      age: "60",
      its: "40434852",
      name: "Fatematussugra bai Mohammedali bhai Kathawala",
      gender: "Female",
    },
    { age: "36", its: "40434853", name: "Huzaifa bhai Mohammedali bhai Kathawala", gender: "Male" },
  ],
  [
    { age: "30", its: "40407374", name: "yasmin Mukadam", gender: "Female" },
    { age: "30", its: "30375990", name: "Zainuddin Dalal", gender: "Male" },
    { age: "30", its: "30488479", name: "Zahra Kapasi", gender: "Female" },
    { age: "20", its: "30602765", name: "Batul", gender: "Female" },
    { age: "18", its: "30602765", name: "huzaifa", gender: "Male" },
    { age: "18", its: "40905701", name: "Husain", gender: "Male" },
    { age: "25", its: "30301803", name: "Sakina Zainuddin", gender: "Female" },
  ],
  [{ age: "74", its: "60437804", name: "Rashida bai Sadiq bhai Patanwalla", gender: "Female" }],
  [
    { age: "63", its: "30377997", name: "Anis bhai Saifuddin bhai Karmalawala", gender: "Male" },
    { age: "38", its: "30378000", name: "Hussain bhai Anis bhai Karmalawala", gender: "Male" },
    { age: "62", its: "60461562", name: "Shaheen bai Anis bhai Karmalawala", gender: "Female" },
  ],
  [
    { age: "51", its: "30343224", name: "Fatema bai Idris bhai Indorewala", gender: "Female" },
    { age: "31", its: "30343225", name: "Ruqaiyah bai Idris bhai Indorewala", gender: "Female" },
    { age: "18", its: "0", name: "Amatullah", gender: "Female" },
  ],
  [{ age: "20", its: "30909528", name: "Mariyam Sadriwala", gender: "Female" }],
  [
    { age: "44", its: "30315766", name: "Fatema bai Huzaifa bhai Diwan", gender: "Female" },
    { age: "16", its: "30905131", name: "Abdulqadir bhai Huzaifa bhai Diwan", gender: "Male" },
  ],
  [
    {
      age: "40",
      its: "30460186",
      name: "Alefiyah bai Adnan bhai Aurangabadwala",
      gender: "Female",
    },
    {
      age: "74",
      its: "40407669",
      name: "Farida bai Shaikh Saifuddin bhai Aurangabadwala",
      gender: "Female",
    },
    {
      age: "45",
      its: "40407670",
      name: "Adnan bhai Shaikh Saifuddin bhai Aurangabadwala",
      gender: "Male",
    },
    { age: "16", its: "40800151", name: "Taher bhai Adnan bhai Aurangabadwala", gender: "Male" },
    {
      age: "12",
      its: "40914558",
      name: "Durratulmajd bai Adnan bhai Aurangabadwala",
      gender: "Female",
    },
  ],
  [
    {
      age: "60",
      its: "30375033",
      name: "Mulla Safiyuddin bhai Mulla Shujauddin bhai Noorani",
      gender: "Male",
    },
    {
      age: "61",
      its: "30375034",
      name: "Shehrebanu bai Mulla Safiyuddin bhai Noorani",
      gender: "Female",
    },
    {
      age: "48",
      its: "30375035",
      name: "Mulla Moayyad bhai Mulla Shujauddin bhai Noorani",
      gender: "Male",
    },
    {
      age: "45",
      its: "30375036",
      name: "Alefiyah bai Mulla Moayyad bhai Noorani",
      gender: "Female",
    },
    { age: "25", its: "30497278", name: "Nafisa bai Murtaza bhai Noorani", gender: "Female" },
    {
      age: "20",
      its: "30709027",
      name: "Shehrebanu bai Mulla Moayyad bhai Noorani",
      gender: "Female",
    },
    {
      age: "27",
      its: "30709028",
      name: "Murtaza bhai Mulla Safiyuddin bhai Noorani",
      gender: "Male",
    },
    {
      age: "32",
      its: "30709029",
      name: "Burhanuddin bhai Mulla Safiyuddin bhai Noorani",
      gender: "Male",
    },
    {
      age: "16",
      its: "40903678",
      name: "Aliasgar bhai Mulla Moayyad bhai Noorani",
      gender: "Male",
    },
    { age: "27", its: "40420136", name: "Durratulmajd Noorani", gender: "Female" },
  ],
  [
    {
      age: "50",
      its: "30423533",
      name: "Munira bai Shaikh Abbas bhai Pardiwala",
      gender: "Female",
    },
    { age: "25", its: "30423534", name: "Aamena bai Mustafa bhai Motiwala", gender: "Female" },
    { age: "23", its: "30423535", name: "Batul bai Mustafa bhai Motiwala", gender: "Female" },
  ],
  [
    { age: "55", its: "20314909", name: "Murtaza bhai Moiz bhai Attarwala", gender: "Male" },
    { age: "21", its: "30401074", name: "Qusai bhai Murtaza bhai Attarwala", gender: "Male" },
    { age: "25", its: "30401075", name: "Alefiyah bai Murtaza bhai Attarwala", gender: "Female" },
    { age: "54", its: "30401076", name: "Lulua bai Murtaza bhai Attarwala", gender: "Female" },
  ],
  [
    { age: "31", its: "30388206", name: "Sakina bai Taher bhai Hamid", gender: "Female" },
    { age: "34", its: "30436520", name: "Taher bhai Zohair bhai Hamid", gender: "Male" },
  ],
  [
    {
      age: "11",
      its: "30116318",
      name: "Burhanuddin bhai Mohammed bhai Ratlamwala",
      gender: "Male",
    },
    { age: "38", its: "30377541", name: "Mohammed bhai Murtaza bhai Ratlamwala", gender: "Male" },
    { age: "8", its: "40185090", name: "Murtaza bhai Mohammed bhai Ratlamwala", gender: "Male" },
    { age: "33", its: "60427900", name: "Zainab bai Mohammed bhai Ratlamwala", gender: "Female" },
  ],
  [
    { age: "8", its: "40153238", name: "Burhanuddin bhai Abbas bhai Poonawala", gender: "Male" },
    { age: "35", its: "60430519", name: "Abbas bhai Mustafa bhai Poonawala", gender: "Male" },
    { age: "28", its: "60436956", name: "Zahabiyah bai Abbas bhai Poonawala", gender: "Female" },
  ],
  [{ age: "36", its: "60468321", name: "Zainab bai Abbas bhai Jamena", gender: "Female" }],
  [{ age: "54", its: "30377707", name: "Almas bai Saifuddin bhai Bharmal", gender: "Female" }],
  [
    { age: "47", its: "30466109", name: "Shoeb bhai Shaikh Yusuf bhai Jasdanwala", gender: "Male" },
    { age: "19", its: "40472678", name: "Zainab bai Shoeb bhai Jasdanwala", gender: "Female" },
    { age: "39", its: "40477783", name: "Ruqaiyah bai Shoeb bhai Jasdanwala", gender: "Female" },
  ],
  [{ age: "16", its: "40420184", name: "Mulla Zohair Aga", gender: "Male" }],
  [
    { age: "46", its: "40434823", name: "Mufaddal bhai Asgar bhai Nalwala", gender: "Male" },
    { age: "39", its: "40434824", name: "Fatema bai Mufaddal bhai Nalwala", gender: "Female" },
  ],
  [
    { age: "13", its: "40916938", name: "Mariya bai Kaizar bhai Ghadiali", gender: "Female" },
    { age: "38", its: "60455721", name: "Shehrebanu bai Kaizar bhai Ghadiali", gender: "Female" },
    { age: "41", its: "60485861", name: "Kaizar bhai Firoz bhai Ghadiali", gender: "Male" },
  ],
  [
    { age: "71", its: "20320794", name: "Shabbir bhai Saifuddin bhai Bookwala", gender: "Male" },
    { age: "66", its: "20325794", name: "Nafisa bai Shabbir bhai Bookwala", gender: "Female" },
  ],
  [
    { age: "52", its: "20402937", name: "Aliasgar Plumber", gender: "Male" },
    { age: "46", its: "60461132", name: "Maria Plumber", gender: "Female" },
  ],
  [
    { age: "55", its: "99999999", name: "Husain", gender: "Male" },
    { age: "45", its: "99999999", name: "Tasneem ", gender: "Female" },
    { age: "12", its: "99999999", name: "Mustafa", gender: "Male" },
    { age: "10", its: "99999999", name: "MAriya", gender: "Female" },
  ],
  [
    {
      age: "45",
      its: "30700907",
      name: "Khuzaima bhai Khurshidhusain bhai Nagarwala",
      gender: "Male",
    },
  ],
  [
    { age: "53", its: "30708937", name: "Murtaza bhai Mohammed bhai Badshah", gender: "Male" },
    { age: "43", its: "30708938", name: "Shireen bai Murtaza bhai Badshah", gender: "Female" },
    { age: "18", its: "30708939", name: "Zainab bai Murtaza bhai Badshah", gender: "Female" },
    { age: "12", its: "50204112", name: "Huzefa bhai Murtaza bhai Badshah", gender: "Male" },
  ],
  [
    { age: "45", its: "30388633", name: "Farida bai Shabbir bhai Gulbadan", gender: "Female" },
    {
      age: "57",
      its: "40467268",
      name: "Shabbir bhai Shaikh Mustafa bhai Gulbadan",
      gender: "Male",
    },
    { age: "17", its: "40900337", name: "Burhanuddin bhai Shabbir bhai Gulbadan", gender: "Male" },
    { age: "13", its: "40917115", name: "Zahra bai Shabbir bhai Gulbadan", gender: "Female" },
  ],
  [{ age: "41", its: "30376140", name: "Abdulqadir bhai Abbas bhai Polishwala", gender: "Male" }],
  [{ age: "81", its: "60461001", name: "Zainab bai Asgarali bhai Bharmal", gender: "Female" }],
  [
    {
      age: "10",
      its: "30117165",
      name: "Mohammed bhai Mulla Murtaza bhai Primaswala",
      gender: "Male",
    },
    {
      age: "40",
      its: "30301813",
      name: "Fatema bai Mulla Murtaza bhai Primaswala",
      gender: "Female",
    },
    {
      age: "45",
      its: "30431789",
      name: "Mulla Murtaza bhai Asgarali bhai Primaswala",
      gender: "Male",
    },
    {
      age: "13",
      its: "40906924",
      name: "Abdulqadir bhai Mulla Murtaza bhai Primaswala",
      gender: "Male",
    },
    { age: "68", its: "20307017", name: "Nakiqa Ben Poonawala", gender: "Female" },
    { age: "50", its: "30905158", name: "Quresh primaswala", gender: "Male" },
    { age: "45", its: "30912199", name: "Munira Primaswala", gender: "Female" },
    { age: "22", its: "30912198", name: "Hussain primaswala", gender: "Male" },
    { age: "17", its: "30912190", name: "Amatulla Primaswala", gender: "Female" },
    { age: "30", its: "30912189", name: "Tasneem Primaswala", gender: "Female" },
    { age: "55", its: "30304419", name: "Farida Mukhtiyar", gender: "Female" },
    { age: "40", its: "30911712", name: "Hasnain Dalal", gender: "Male" },
    { age: "43", its: "30376517", name: "Sakina primuswala", gender: "Female" },
  ],
  [
    {
      age: "46",
      its: "50483813",
      name: "Mulla Murtaza bhai Shaikh Qutbuddin bhai Tinwala",
      gender: "Male",
    },
    {
      age: "39",
      its: "50483814",
      name: "Alefiyah bai Mulla Murtaza bhai Tinwala",
      gender: "Female",
    },
    { age: "17", its: "60413063", name: "Moiz bhai Mulla Murtaza bhai Tinwala", gender: "Male" },
  ],
  [
    {
      age: "58",
      its: "20326568",
      name: "Abbas bhai Sajjadhusain bhai Phaltanwala",
      gender: "Male",
    },
    { age: "21", its: "30377753", name: "Ummehani bai Huzaifa bhai Rahim", gender: "Female" },
  ],
  [
    { age: "66", its: "20326559", name: "Salma bai Khanali bhai Rampurawala", gender: "Female" },
    { age: "17", its: "0", name: "Mariyah Abbasbhai", gender: "Female" },
  ],
  [
    { age: "72", its: "40407128", name: "Salma PRatapgarhwala", gender: "Female" },
    { age: "40", its: "30374672", name: "Yusuf PRatapgarhwala", gender: "Male" },
    { age: "35", its: "3045582", name: "Alefiyah", gender: "Female" },
    { age: "8", its: "30156334", name: "Batul ", gender: "Female" },
    { age: "6", its: "30156346", name: "Mudar", gender: "Male" },
  ],
  [{ age: "57", its: "20389960", name: "Fakhruddin bhai Huseini bhai Padiwala", gender: "Male" }],
  [
    { age: "50", its: "30368999", name: "Mustafa bhai Hatimali bhai Kothawala", gender: "Male" },
    { age: "21", its: "30369000", name: "Zahra bai Mustafa bhai Kothawala", gender: "Female" },
    { age: "47", its: "30372352", name: "Arwa bai Mustafa bhai Kothawala", gender: "Female" },
    { age: "10", its: "40156370", name: "Fatema bai Mustafa bhai Kothawala", gender: "Female" },
  ],
  [
    { age: "60", its: "20352819", name: "Shaikh Moiz bhai Ibrahim bhai Jetaji", gender: "Male" },
    { age: "51", its: "30488332", name: "Farida bai Shaikh Moiz bhai Jetaji", gender: "Female" },
    { age: "27", its: "30488331", name: "Sakina Jetaji", gender: "Female" },
  ],
  [
    { age: "44", its: "30376235", name: "Rashida bai Murtaza bhai Ghadialy", gender: "Female" },
    { age: "16", its: "30801906", name: "Batul bai Murtaza bhai Ghadiyali", gender: "Female" },
  ],
  [
    { age: "24", its: "30389723", name: "Rabab bai Burhanuddin bhai Ansari", gender: "Female" },
    { age: "34", its: "30465940", name: "Huzaifa bhai Mehdi bhai Ansari", gender: "Male" },
    { age: "32", its: "30465941", name: "Burhanuddin bhai Mehdi bhai Ansari", gender: "Male" },
    { age: "59", its: "30465942", name: "Banu bai Mehdi bhai Ansari", gender: "Female" },
    { age: "65", its: "30465943", name: "Mehdi bhai Fazalehusain bhai Ansari", gender: "Male" },
    { age: "33", its: "50436254", name: "Ummehani bai Huzaifa bhai Ansari", gender: "Female" },
  ],
  [
    {
      age: "48",
      its: "20325454",
      name: "Shabbir bhai Shaikh Saifuddin bhai Aamir",
      gender: "Male",
    },
    { age: "15", its: "30914200", name: "Jamila bai Shabbir bhai Aamir", gender: "Female" },
    { age: "44", its: "40434860", name: "Shehrebanu bai Shabbir bhai Aamir", gender: "Female" },
    { age: "21", its: "40434861", name: "Insiyah bai Shabbir bhai Aamir", gender: "Female" },
    { age: "9", its: "50183006", name: "Mariya bai Shabbir bhai Aamir", gender: "Female" },
  ],
  [
    {
      age: "74",
      its: "20357540",
      name: "Shaikh Abdulhusain bhai Fidahusain bhai Kachwala",
      gender: "Male",
    },
    {
      age: "41",
      its: "30461749",
      name: "Huzaifa bhai Shaikh Abdulhusain bhai Kachwala",
      gender: "Male",
    },
    {
      age: "69",
      its: "30461750",
      name: "Maleka bai Shaikh Abdulhusain bhai Kachwala",
      gender: "Female",
    },
    { age: "13", its: "30924429", name: "Sakina bai Huzaifa bhai Kachwala", gender: "Female" },
    { age: "38", its: "60422895", name: "Alefiyah bai Huzaifa bhai Kachwala", gender: "Female" },
  ],
  [
    { age: "9", its: "30152571", name: "Fatema bai Abdulqadir bhai Kothawala", gender: "Female" },
    { age: "51", its: "30368996", name: "Abdulqadir bhai Hatimali bhai Kothawala", gender: "Male" },
    { age: "47", its: "30368997", name: "Tasneem bai Abdulqadir bhai Kothawala", gender: "Female" },
  ],
  [
    { age: "27", its: "30466075", name: "Mohammed bhai Mustafa bhai Ansari", gender: "Male" },
    { age: "57", its: "30466079", name: "Mustafa bhai Qutbuddin bhai Ansari", gender: "Male" },
    { age: "52", its: "30466082", name: "Rizwana bai Mustafa bhai Ansari", gender: "Female" },
    { age: "28", its: "40451276", name: "Munira bai Husain bhai Ansari", gender: "Female" },
  ],
  [
    { age: "35", its: "30708084", name: "Habib bhai Shabbir bhai Titi", gender: "Male" },
    { age: "37", its: "0", name: "Aliasgar Titi", gender: "Male" },
    { age: "64", its: "30708267", name: "Shabbir Titi", gender: "Male" },
    { age: "36", its: "30376005", name: "Farah Titi", gender: "Female" },
    { age: "63", its: "20325732", name: "Yasmin Shaikh", gender: "Female" },
  ],
  [
    {
      age: "71",
      its: "20326704",
      name: "Zainab bai Mulla Yusuf bhai Vansvadawala",
      gender: "Female",
    },
    { age: "42", its: "30374347", name: "Rashida bai Mustafa bhai Vanswadawala", gender: "Female" },
  ],
  [
    { age: "51", its: "50414608", name: "Munira bai Hatim bhai Fanuswala", gender: "Female" },
    { age: "22", its: "50414610", name: "Abbas bhai Huzaifa bhai Kalaiwala", gender: "Male" },
    { age: "21", its: "30377386", name: "Adnan Khandwala", gender: "Male" },
  ],
  [
    { age: "69", its: "20432794", name: "Husaini bhai Ishaqali bhai Ronak", gender: "Male" },
    { age: "66", its: "40484548", name: "Zarina bai Husaini bhai Ronak", gender: "Female" },
    { age: "35", its: "50424550", name: "Sakina bai Aliasgar bhai Ronak", gender: "Female" },
  ],
  [
    {
      age: "78",
      its: "20394391",
      name: "Firoz bhai Mulla Abdulhusain bhai Broachwala",
      gender: "Male",
    },
  ],
  [
    {
      age: "56",
      its: "20320504",
      name: "Shabbir bhai Mulla Qutbuddin bhai Katabjiwala",
      gender: "Male",
    },
    { age: "46", its: "50440580", name: "Sugra bai Shabbir bhai Katabjiwala", gender: "Female" },
  ],
  [
    { age: "62", its: "20412053", name: "Shabbir bhai Zoeb bhai Kothari", gender: "Male" },
    { age: "24", its: "30804845", name: "Zahabiyah bai Murtaza bhai Kothari", gender: "Female" },
    { age: "59", its: "50430787", name: "Rashida bai Shabbir bhai Kothari", gender: "Female" },
    { age: "31", its: "50430788", name: "Murtaza bhai Shabbir bhai Kothari", gender: "Male" },
  ],
  [
    { age: "57", its: "20325644", name: "Saifuddin bhai Yusuf bhai Trivedi", gender: "Male" },
    { age: "23", its: "30376515", name: "Husain bhai Saifuddin bhai Trivedi", gender: "Male" },
    { age: "42", its: "30376519", name: "Fatema bai Saifuddin bhai Trivedi", gender: "Female" },
  ],
  [{ age: "47", its: "30413533", name: "Fatema bai Abdulhusain bhai Hakim", gender: "Female" }],
  [
    {
      age: "76",
      its: "20345053",
      name: "Mulla Fakhruddin bhai Yahya bhai Takulla",
      gender: "Male",
    },
    {
      age: "71",
      its: "30454152",
      name: "Rashida bai Mulla Fakhruddin bhai Takulla",
      gender: "Female",
    },
  ],
  [
    { age: "54", its: "40420190", name: "M. Abitamim Hamid", gender: "Male" },
    { age: "45", its: "40420189", name: "Mariya Hamid", gender: "Female" },
    { age: "21", its: "40420187", name: "M. Taha Hamid", gender: "Male" },
  ],
  [
    { age: "42", its: "40407108", name: "Zainab Sh Adnan", gender: "Female" },
    { age: "19", its: "40900542", name: "Fatema Sh Adnan", gender: "Female" },
    { age: "15", its: "40900543", name: "Abdulqadir Sh Adnan", gender: "Male" },
    { age: "14", its: "40903122", name: "Batul Sh Adnan", gender: "Female" },
    { age: "12", its: "40152094", name: "Zahra Sh Adnan", gender: "Female" },
    { age: "55", its: "40407397", name: "Shk Adnan Bandukwala", gender: "Male" },
  ],
  [
    { age: "49", its: "30374105", name: "Tasneem bai Shabbir bhai Tandiwala", gender: "Female" },
    {
      age: "55",
      its: "30374106",
      name: "Shabbir bhai Shaikh Husain bhai Tandiwala",
      gender: "Male",
    },
    { age: "48", its: "60413544", name: "Zainab Tinwala", gender: "Female" },
  ],
  [{ age: "53", its: "30377453", name: "Rashida bai Shakir bhai Nashikwala", gender: "Female" }],
  [
    {
      age: "28",
      its: "30375107",
      name: "Aliasgar bhai Mulla Fakhruddin bhai Husainy",
      gender: "Male",
    },
    { age: "26", its: "60454215", name: "Fatema bai Aliasgar bhai Husainy", gender: "Female" },
  ],
  [
    { age: "18", its: "30610871", name: "Marya bai Hatim bhai Godhrawala", gender: "Female" },
    { age: "44", its: "30610873", name: "Hatim bhai Tayyeb bhai Godhrawala", gender: "Male" },
    { age: "40", its: "30610874", name: "Rashida bai Hatim bhai Godhrawala", gender: "Female" },
    { age: "71", its: "30610876", name: "Farida bai Tayyeb bhai Godhrawala", gender: "Female" },
  ],
  [
    { age: "39", its: "30433366", name: "Razia bai Mulla Kaizar bhai Bharucha", gender: "Female" },
    { age: "13", its: "40908283", name: "Asma bai Mulla Kaizar bhai Bharucha", gender: "Female" },
    { age: "67", its: "50481250", name: "Nafisa bai Javed bhai Bharucha", gender: "Female" },
    { age: "43", its: "50481251", name: "Mulla Kaizar bhai Javed bhai Bharucha", gender: "Male" },
  ],
  [
    { age: "62", its: "60461170", name: "Munira Khokhawala", gender: "Female" },
    { age: "40", its: "60461171", name: "Murtaza Khokhawala", gender: "Male" },
    { age: "35", its: "30447681", name: "Ummekulsum Khokhawala", gender: "Female" },
    { age: "15", its: "40903651", name: "Nisreen Khokhawala", gender: "Female" },
  ],
  [{ age: "80", its: "20440762", name: "Asgarali bhai Taherali bhai Pardawala", gender: "Male" }],
  [{ age: "25", its: "30399133", name: "Ammar Kuwarawala", gender: "Male" }],
  [
    { age: "32", its: "30438245", name: "Mustafa bhai Shaikh Zoeb bhai Kallawala", gender: "Male" },
    { age: "25", its: "30455580", name: "Shehrebanu bai Mustafa bhai Kallawala", gender: "Female" },
    { age: "75", its: "20357488", name: "Shk Zoyeb bhai Kallawala", gender: "Male" },
    { age: "65", its: "30438244", name: "Ajab ben Shk Zoyeb bhai Kallawala ", gender: "Female" },
  ],
];
