export const sabils = [
  {
    SabilId: 1,
    SabilNo: "SMM-1",
    ItsId: 20359199,
    YearlyAmount: 786.0,
    PaidTill: "2020-03-31T00:00:00",
    Status: 0,
    Mohallah: "Others",
    PAN: "",
    TransferTo: "",
    Remark: "",
    Category: 1,
    Mumeen: {
      eJamaatID: 0,
      HOF_ID: 20359199,
      f_prefix: "SHK",
      First_name: "ISHAQ",
      L_name: "GODHRAWALA",
      Marital: "Married",
      Father_Name: "ABBAS BHAI",
      Husband_Name: "",
      email: null,
      Nationality: null,
      Occupation: null,
      Housing: null,
      Type_of_House: null,
      Building_name: null,
      Street_name: null,
      Area: null,
      address: "KONDHWA",
      Gender: "M",
      MOBILE_NO: "8983014652",
      Mohallah: null,
      Remarks: null,
      Age: 0,
      SubOccupation: null,
      Masool: "",
      Musaed: "",
    },
  },
  {
    SabilId: 2,
    SabilNo: "SMM-2",
    ItsId: 20317707,
    YearlyAmount: 2558.0,
    PaidTill: "2019-11-30T00:00:00",
    Status: 2,
    Mohallah: "Other",
    PAN: "",
    TransferTo: "",
    Remark: "",
    Category: 1,
    Mumeen: {
      eJamaatID: 0,
      HOF_ID: 20317707,
      f_prefix: "",
      First_name: "Haiderali",
      L_name: "Kotwala",
      Marital: "Married",
      Father_Name: "Abdeali",
      Husband_Name: "",
      email: null,
      Nationality: null,
      Occupation: null,
      Housing: null,
      Type_of_House: null,
      Building_name: null,
      Street_name: null,
      Area: null,
      address: "B1-4,1st Floor,Badshah Nagar,Kondhwa Khurd,Opp Kon",
      Gender: "M",
      MOBILE_NO: "+918668874388",
      Mohallah: null,
      Remarks: null,
      Age: 0,
      SubOccupation: null,
      Masool: "Ahmed bhai  Mohsinali bhai Vaghjipurwala",
      Musaed: "",
    },
  },
];
